### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by kentcdodds** [all-contributors/all-contributors#112]
Hey folks,

I'm drowning in GitHub notification emails and need to lighten my load. So with heavy heart I'm picking a few projects to detach myself from and unfortunately this is one of them.

I would like to hand this project off to someone who's _already_ been contributing to the project (I'd like to avoid another incident like [this](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/)). If you would like to take ownership of this project, please let me know by emailing me at the address found on my github profile.

I'm unwatching this repository effective immediately. I'm sorry about that, but I've just been stretched too thin. Even if nobody takes up the maintenance of this project, it works well in its current form for its current users and I hope that's good enough until someone is willing to take up the mantel as maintainer.

**Comment by Berkmann18** [comment]
I'll be happy to help although I don't think I'll be able to do this on my own given that I'm still unfamiliar with codebase.
But anything that would fall under pretty much all the contribution types namely: code, test, design, docs; would be areas where I'm willing to help.

**Comment by MatheusRV** [comment]
I'm still here, not time at this moment but soon as possible i could review pt-br translated.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this as we've got a great few maintainers now :)
