### ISSUE TITLE
Do not use dynamic version hover translated version

### ISSUE THREAD

**Issue by MatheusRV** [all-contributors/all-contributors#134]
Please remove the dynamic use of the emoji table version, this has been implemented to show that the translation is outdated or not from the original version. As you can see in the portuguese version of brazil https://github.com/all-contributors/all-contributors/blob/master/docs/en/README.md#tabela-de-emoji-v270 the table version is in 2.7 and the project in 2.7.1 which means that something is missing. Thus facilitating the life of the translators.

**Comment by Berkmann18** [comment]
With what @jakebolam implemented on all-contributors-bot (after what happened with the addition of Korean translations) this issue should be resolved.

**Comment by jakebolam** [comment]
@MatheusRV are you referring to doing this? #135

Also related: #136

**Comment by MatheusRV** [comment]
Yes, tks closing this!
