### ISSUE TITLE
Add Maintenance in Contributor List

### ISSUE THREAD

**Issue by MatheusRV** [all-contributors/all-contributors#140]

**Comment by Berkmann18** [comment]
Is that to add the maintenance category to whom it applies to?

**Comment by MatheusRV** [comment]
> Is that to add the maintenance category to whom it applies to?

Yes, you and @jakebolam isnt with maintence emoji.

**Comment by Berkmann18** [comment]
Good call
@allcontributors please add @jakebolam and @Berkmann18 for maintenance

**Comment by MatheusRV** [comment]
@Berkmann18 he dont add you
