### ISSUE TITLE
Project Manager 

### ISSUE THREAD

**Issue by MatheusRV** [all-contributors/all-contributors#141]
I sugest 📋 (Clipboard)

**Comment by Berkmann18** [comment]
I like that but it's already used for _event organisation_, some alternative choices would be 📜 or 🗒.

**Comment by jakebolam** [comment]
I like the idea

**Comment by Berkmann18** [comment]
Or 📆 ?

**Comment by MatheusRV** [comment]
> Or 📆 ?

Nice for event..

**Comment by sinchang** [comment]
agree with your idea 📆 cc @Berkmann18
