### ISSUE TITLE
Consolidate readme information into central place

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#142]
This work has been completed on:
- https://github.com/all-contributors/all-contributors-bot
- https://github.com/all-contributors/all-contributors-cli

I believe the next step is to consolidate the specification information available in this readme. So the website becomes the single source of truth. 

I think we should do this, once the website has additional languages: https://github.com/all-contributors/website/issues/10

**Comment by jakebolam** [comment]
Most information is on the website (https://all-contributors.js.org), with a great new homepage! Waiting for the results of #150, a little more translating in #143. and some better SEO for the final centralization.

**Comment by Berkmann18** [comment]
@jakebolam Do you if the @all-contributors-release-bot is the same as @all-contributors (from a contributors' perspective)?
If so I'll ask it to add itself for `platform`.

**Comment by Berkmann18** [comment]
Whoops! I didn't expect it to understand that.
