### ISSUE TITLE
Links are being translated resulting in broken URLs

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#156]
E.g. https://all-contributors.js.org/docs/zh-CN/仓库维护人员

**Comment by jakebolam** [comment]
Good spot, yeah will need to look at that too.
I think its coming from: https://docusaurus.io/docs/en/doc-markdown#generating-table-of-contents

**Comment by jakebolam** [comment]
It looks like we can hide the hidden strings, and prevent the problem occurring by just keeping everyone as translators.
https://support.crowdin.com/online-editor/
>  hidden (visible only for project managers and proofreaders)

**Comment by Berkmann18** [comment]
This issue seems to be fixed.

**Comment by MatheusRV** [comment]
Still geting a 404 on https://github.com/all-contributors/all-contributors/blame/master/README.md#L17

**Comment by codimiracle** [comment]
i fixed it in my repo: https://github.com/codimiracle/all-contributors @MatheusRV

**Comment by Berkmann18** [comment]
@MatheusRV Oh! that's due to a typo.
Well spotted.

**Comment by codimiracle** [comment]
Ofcourse!

**Comment by codimiracle** [comment]
https://allcontributors.org/docs/zh-CN/%E5%B7%A5%E5%85%B7

**Comment by codimiracle** [comment]
page not found list:
https://allcontributors.org/docs/zh-CN/工具
in page follows:
https://allcontributors.org/docs/zh-CN/repository-maintainers
https://allcontributors.org/docs/zh-CN/emoji-key
----
https://allcontributors.org/docs/zh-CN/bot/安装
in page:
https://allcontributors.org/docs/zh-CN/bot/overview
----
https://allcontributors.org/docs/zh-CN/bot/用法
in page:
https://allcontributors.org/docs/zh-CN/bot/overview
---
is it fixing? @Berkmann18

**Comment by jakebolam** [comment]
We run a 404 check after every deploy to find issues. Last run results: https://circleci.com/gh/all-contributors/all-contributors/358
