### ISSUE TITLE
Ensure search is only for the current language

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#158]
Tweak this setting: https://github.com/all-contributors/website/blob/master/website/siteConfig.js#L51

See documentation: https://docusaurus.io/docs/en/search#docsNav

**Comment by jakebolam** [comment]
FYI algiolia side settings: https://github.com/algolia/docsearch-configs/blob/master/configs/all-contributors.json

**Comment by s-pace** [comment]
TIP: Once this settings is done from siteConfig, please ensure that you do not inject the following snippet two times :)
![image](https://user-images.githubusercontent.com/32097720/53105785-02048b80-3532-11e9-9535-a31d5735b11a.png)
