### ISSUE TITLE
Community profile checklist

### ISSUE THREAD

**Issue by Berkmann18** [all-contributors/all-contributors#165]
This repo, as of now, has an incomplete [community checklist](https://github.com/all-contributors/all-contributors/community) and it would be good to check more items to improve its community profile.

## What can you do?
1. Check that the community checklists on:
- [AC-CLI](https://github.com/all-contributors/all-contributors-cli/community)
- [AC-bot](https://github.com/all-contributors/all-contributors-bot/community)

Are all in sync with this repo's one.
2. Fill in the blanks with what's missing in one of the repos but not all.
3. Add what's missing to this repo then to the others (once you get the initial PRs merged).
4. Get yourself on the contributor's list (if you're not already there).

**Comment by simonhoyos** [comment]
@Berkmann18 I can help with this one if it's still available

**Comment by Berkmann18** [comment]
@simonhoyos Awesome, feel free to submit a PR.

**Comment by simonhoyos** [comment]
@Berkmann18 great, I'll start working on this one later tonight and will open a PR ASAP

**Comment by Berkmann18** [comment]
@simonhoyos Great, looking forward to it 😄.

**Comment by simonhoyos** [comment]
@Berkmann18, none of these three projects has a code of conduct but checking contributing documentation I found one. 

Would it be nice to add it to the project?

**Comment by Berkmann18** [comment]
@simonhoyos This repo [has one](https://github.com/all-contributors/all-contributors/blob/master/CODE_OF_CONDUCT.md), not sure why it's not checked on the community even tho it's pointing to it, same goes for the bot repo. The CLI repo, on the other hand indeed does have one.
So see what you can do to resolve that.

**Comment by saoodahmad** [comment]
hi, is the issue still open as I can see a pr has been already merged?

**Comment by tenshiAMD** [comment]
Done using organization `.github` repo.
