### ISSUE TITLE
Switch to netlify

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#172]
Should we switch hosting from github-pages to netlify?

https://www.netlify.com/github-pages-vs-netlify/

**Comment by Berkmann18** [comment]
I'm down for trying netlify which seems better for us.

**Comment by Berkmann18** [comment]
Should we keep the `gh-pages` for deployments on Netlify or should we switch to `master`?

**Comment by jakebolam** [comment]
Closed in #211
