### ISSUE TITLE
Commands are not generated in translated CLI Usage documentation

### ISSUE THREAD

**Issue by dance2die** [all-contributors/all-contributors#196]
I found out that the command list is not auto-generated in Korean documentation.
English Doc: https://allcontributors.org/docs/en/cli/usage#commands
Korean Doc: https://allcontributors.org/docs/ko/cli/usage#%EC%BD%94%EB%A9%98%EB%93%9C%EB%93%A4

![error image](https://user-images.githubusercontent.com/8465237/52758600-ea2f8380-2fd6-11e9-9e28-29f5b2545844.png)

_______________
_______________

* The problem occurs in all other languages
_______________
_______________

![chrome_2019-02-13_21-35-26](https://user-images.githubusercontent.com/8465237/52758837-c6207200-2fd7-11e9-9b9e-89d68788f567.png)

**Comment by jakebolam** [comment]
Thanks for the catch.

I'm not sure what's going on. Looks like it should work at documented on the docusauraus docs.

Filed an issue (please add additional context of missing) https://github.com/facebook/Docusaurus/issues/1234

**Comment by Berkmann18** [comment]
@jakebolam This is most likely due to the removal of the ToC on the CLI's README (remember our discussion on removing that?).

**Comment by dance2die** [comment]
Thank you for taking an action to resolve this issue 🙂

**Comment by tenshiAMD** [comment]
Looks like this is irrelevant now. Closing this for now.
