### ISSUE TITLE
Violation of attribution policy: Missing Algolia logo on search. 

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#201]
## Issue
It seems that the Algolia logo has been removed from the footer of the dropdown thanks to a background CSS rule:
![alogila](https://user-images.githubusercontent.com/3534236/53105253-c13f4f00-34fe-11e9-8bf7-76998a3df020.png)
We need to put this logo back since it is mandatory as part of Aloglia's attribution policy.

## Should be
![screen shot 2019-02-20 at 10 58 53 am](https://user-images.githubusercontent.com/3534236/53105273-c8665d00-34fe-11e9-82e4-b6ed874d2b67.png)

Thanks to @s-pace for reporting this.

**Comment by s-pace** [comment]
For reference, you can [see our attribution policy here](https://community.algolia.com/docsearch/styling.html#attribution).

Thank you for the quick follow up

**Comment by jakebolam** [comment]
@all-contributors please add @s-pace for plugins

**Comment by Berkmann18** [comment]
Is that only translated versions __and__ the English one or just translated ones?

**Comment by s-pace** [comment]
Thanks @Berkmann18

**Comment by Berkmann18** [comment]
@s-pace Thanks, the credits go to @sinchang for #206.

**Comment by s-pace** [comment]
Thanks @sinchang :)

**Comment by jakebolam** [comment]
Fixed it for all of docusauraus. Legend @sinchang
