### ISSUE TITLE
all-contributors.js.org looks too much like allcontributors.org

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#218]
The landing page on the old domain, looks nearlly identical to the real site. We should considering changing the redirect-landing page to avoid confusion.

### all-contributors.js.org
![screen shot 2019-02-23 at 9 02 28 pm](https://user-images.githubusercontent.com/3534236/53294111-7a778080-37ae-11e9-91f1-8520907b11d4.png)

### allcontributors.org
![screen shot 2019-02-23 at 9 02 31 pm](https://user-images.githubusercontent.com/3534236/53294113-7e0b0780-37ae-11e9-9140-5e7c95e7cce1.png)

**Comment by Berkmann18** [comment]
I guess having the "all-contributors ... has moved ..." message closer to the centre, in red and perhaps in a bigger font-size would be UX-wise good enough to indicate which one is the _correct_ website.

**Comment by tbenning** [comment]
Great idea @jakebolam! It will be helpful to change the look, so it not confusing for users. So long as the call to action (link) is clearly visible it will work great for users. Red might be alarming or make users think they've made an error. 

Keep an eye on the traffic coming in on the new page and we should be fine!
