### ISSUE TITLE
Add all code contributors in repo to contributors list

### ISSUE THREAD

**Issue by imolorhe** [all-contributors/all-contributors#229]
Hey there, is there a way to automagically add all the people that have contributed to a repo to the contributors list without having to manually enter each person?

This is especially needed for a repo that is already active with quite a number of contributors and wants to include allcontributors.

**Comment by Berkmann18** [comment]
Not yet, but it's on table.

**Comment by imolorhe** [comment]
Okay. Good to know. Thanks!

**Comment by Berkmann18** [comment]
In the meantime feel free to contribute if you wish.
