### ISSUE TITLE
Proposal: Remove all-contributors publishing to NPM

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors#234]
Consider removing the all-contributors-spec publishing to NPM. Instead use another method, perhaps just [GitHub releases](https://github.com/all-contributors/all-contributors/releases) instead.

The npm package `all-contributors-cli` could then use `all-contributors`  or both for publishing.

Thoughts?

**Comment by Berkmann18** [comment]
Well, it's definitely a good idea to remove `all-contributors-spec` from NPM (or making it private) as it seems to mislead people into thinking it's the CLI when it has no use in Node environments.
GitHub releases would be the way to go.
As for `all-contributors-cli` it could just use the GH URL for the dependency.

**Comment by tenshiAMD** [comment]
@jakebolam @Berkmann18 all-contributors-spec cannot be found on NPM anymore. Looks like this is done. Closing this now.
