### ISSUE TITLE
PR another branch except master branch

### ISSUE THREAD

**Issue by MrSyee** [all-contributors/all-contributors#255]
I'd like to suggest an option on which target branch to choose when PR.
Currently using `@all-contributors add` command, only push the master branch.

How would you think about this?

**Comment by Berkmann18** [comment]
That's a good idea.
Would you mind opening a PR for this?

**Comment by jakebolam** [comment]
I believe the bit opens the PR against whatever the repositories default branch is: https://github.com/all-contributors/all-contributors-bot/pull/46

**Comment by MrSyee** [comment]
Thank you! How do I check this update? We use all-Contributors bot. Is there a new bot command for this update?

**Comment by Berkmann18** [comment]
@MrSyee Normally you should have the latest update available (I think).

**Comment by Berkmann18** [comment]
@MrSyee Did you managed to get the latest update on the bot?

**Comment by MrSyee** [comment]
Oh sorry. I check it now. I get the latest update and I use command "@all-contributors please add @MrSyee for code" in repository issue. But it makes PR into master branch that is the base branch. What commands can I use to make PR a different branch of my choosing?

**Comment by MrSyee** [comment]
It is unintended PR :( 
Sorry.

**Comment by Berkmann18** [comment]
@MrSyee Have you checked in a repo where the default branch **is not `master`**?

**Comment by MrSyee** [comment]
The default branch is `master`. Does this command push only in the default branch? I want to push a other branch that I want, for example, If I use "all-contributors please add MrSyee for code to `feature/add-contributor`" it push to `feature/add-contributor` branch. Can I do it?

**Comment by Berkmann18** [comment]
You mean the branch it's merging against right?
The bot automatically creates separate branches for each changes.

**Comment by MrSyee** [comment]
hmm, I want the branch that makes the bot is the target branch. 
Current, as I know it, the bot makes `all-contributors/add-MrSyee` and merge to master.
But I want the bot makes `all-contributors/add-MrSyee` and merge to `feature/my-branch`, for example.

In fact, I think when someone contributes my project with PR of contributors, all-contributor bot update readme in that PR. Then I merge just one PR to master (merge other PR to feature branch of contributors). As I use it when I use bot command in PR, the bot creates new PR to master. In case I merge two PR to master.

I asked the question for that reason.

**Comment by Berkmann18** [comment]
> hmm, I want the branch that makes the bot is the target branch.
Current, as I know it, the bot makes all-contributors/add-MrSyee and merge to master.
But I want the bot makes all-contributors/add-MrSyee and merge to feature/my-branch, for example.

Ah okay, that makes sense.

Would you mind opening a PR on https://github.com/all-contributors/all-contributors-bot?

**Comment by MrSyee** [comment]
I'll try, but it might not work. Thanks for your response.

**Comment by Berkmann18** [comment]
Okay 😀.
