### ISSUE TITLE
Not updating README.md

### ISSUE THREAD

**Issue by K-Sato1995** [all-contributors/all-contributors#257]
**Describe the bug**
After running the `add` command, the bot updates the .all-contributorsrc fine. But it does not update README.md. 
Feel like I'm missing something very simple.

```
@all-contributors please add <username> for <contributions>
```
![image](https://user-images.githubusercontent.com/32632542/56729319-f29efa00-678f-11e9-924c-d1af3d5ec65f.png)

**Expected behavior**
Updates README.md and create the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/32632542/56729319-f29efa00-678f-11e9-924c-d1af3d5ec65f.png)

**Comment by Berkmann18** [comment]
FYI, this is a [bot](https://github.com/all-contributors/all-contributors-bot) issue not a specification/website one.
Have you checked that `.all-contributorsrc` file points to `README.md`?

**Comment by K-Sato1995** [comment]
> FYI, this is a bot issue not a specification/website one.

Should I open this issue there instead??

> Have you checked that .all-contributorsrc file points to README.md?

My ` .all-contributorsrc` is looking something like the following.

```
{
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "contributors": [ ],
}
```

**Comment by Berkmann18** [comment]
@K-Sato1995 Yes.

Your config file seems incomplete, have you checked the [configuration docs](https://allcontributors.org/docs/en/bot/configuration)?

**Comment by K-Sato1995** [comment]
Closing the issue here due to creating the same issue at the proper place.
