### ISSUE TITLE
Synonyms 

### ISSUE THREAD

**Issue by krzkaczor** [all-contributors/all-contributors#274]
**Is your feature request related to a problem? Please describe.**
I tried adding new contributos for `idea` and `docs` but the proper terms where `ideas` and `doc`.

**Describe the solution you'd like**
Solution is to allow synonyms for contribution types. Probably bot, or CLI should always normalize to one form but user interface should be as simple as possible.

**Comment by Berkmann18** [comment]
The bot already supports synonyms and such. The CLI will point out when you're not using the correct terms; at the same time it has prompts which allow you to specify the username and contributions.

**Comment by krzkaczor** [comment]
My experience was that CLI was just ignoring them:

```
all-contributors add someone code idea
```

but now i realized that it was because CLI takes only one argument 🤦‍♂ my fault. Nvm.

I think if synonyms are supported this should be noted in https://allcontributors.org/docs/en/emoji-key

**Comment by Berkmann18** [comment]
@krzkaczor The CLI takes more than one argument unless you're using `check`, `generate` or the upcoming `fetch` one.

> I think if synonyms are supported this should be noted in https://allcontributors.org/docs/en/emoji-key

That's the general emoji-key which don't have the variations (what I meant when I wrote about the bot supporting synonyms) and having synonyms in the spec would make the whole thing unnecessarily complex (especially in areas where there's NO NLP/ML).

**Comment by Berkmann18** [comment]
@krzkaczor Is this still a problem?

**Comment by krzkaczor** [comment]
yeah i think I ll just close this ;) Thanks!
