### ISSUE TITLE
Using all-contributor theme for another open source project?

### ISSUE THREAD

**Issue by boyney123** [all-contributors/all-contributors#278]
Hey 👋 ,

First thing, I love the `all-contributors` project. I use it most my open source work and I think it's great!

I'm currently a huge fan of docusaurus too and love the fact your homepage is built from it.

This might seem like a really random request (not sure if even belongs in an issue?), but I would like to use your theme for my next open source project.

I wanted to run it past you before I go ahead and do it, out of courtesy.

Are you OK with me using it? (Screenshot below), or would you prefer me not too?

I'm cool either way.

Thanks 👍  

![localhost_3001_ (1)](https://user-images.githubusercontent.com/3268013/59019336-c327e680-883f-11e9-8b7c-bda03e9da192.png)

**Comment by Berkmann18** [comment]
@jakebolam @tbenning What do you think?

I wouldn't mind (assuming credits are given where they are due).

**Comment by tbenning** [comment]
As the designer that put this together, I'm cool with it. Go forth with my blessings ✌️

**Comment by boyney123** [comment]
Great thanks 🙇 🙏 👍

**Comment by tbenning** [comment]
@boyney123 One small request! Can you remove the AC logo from your project, so as not to confuse the brands or project? Thanks!

![image](https://user-images.githubusercontent.com/7265547/59455561-4bbaff80-8dc9-11e9-9454-893309359597.png)

**Comment by boyney123** [comment]
Yeah will do, it was on my list of things to do, but Il get it done ASAP 👍

**Comment by boyney123** [comment]
All done @tbenning 

Thanks again for the awesome theme and work 👍 , and letting me use it.
