### ISSUE TITLE
Add a skip-CI option

### ISSUE THREAD

**Issue by fennecdjay** [all-contributors/all-contributors#281]
First off, thanks for the amazing work! :champagne: 

I've recently used the bot, and noticed every commit whould start a CI build,
which might not be desirable for a README/dotfile change.

There should be an option add add something like *[skip ci]* to the commit message.
IMHO, that should be the default.

The only alternative I could think of is disabling PR build on the CI, but that's annoying, as it wouldn't trigger on something useful (code contribution for instance).

Let me know what you think.

**Comment by jakebolam** [comment]
Hey @fennecdjay thanks for the great request, totally sounds reasonable.

How do you feel about an option in the [config file](https://github.com/all-contributors/all-contributors/blob/master/.all-contributorsrc#L2) to supply a custom commit message?

Are you interested in putting up a PR for this. This config file is read into memory under the object `optionsConfig` and the [code that commits the message is here](https://github.com/all-contributors/all-contributors-bot/blob/afcc8753fb0ee8ea0c76a7af6048c2528066bb31/src/tasks/processIssueComment/probot-processIssueComment.js#L65).

**Comment by jakebolam** [comment]
FYI documentation for the current configuration file format: https://allcontributors.org/docs/en/bot/configuration

**Comment by fennecdjay** [comment]
> How do you feel about an option in the config file to supply a custom commit message?

That's exactly what I tried to express :sweat_smile:

I don't know much about *js* but I'll give it a look. (I'm afraid it might take me a long time without further guidance)

Thanks for your detailed answer.

**Comment by fennecdjay** [comment]
Is there anyway to run the bot locally?

**Comment by jakebolam** [comment]
Awesome good luck.

Yes there's some basic documentation here:
https://github.com/all-contributors/all-contributors-bot/blob/master/contributing/run-bot-locally.md

It's built on probot, and follows a roughly similar local development flow
https://probot.github.io/docs/testing/

**Comment by fennecdjay** [comment]
I've git something to show you :smile:
Is it ok if I submit a PR to [the bot repo](https://github.com/all-contributors/all-contributors-bot)?

**Comment by jakebolam** [comment]
@fennecdjay for sure, submit the PR and I can review

**Comment by jakebolam** [comment]
Exciting!

**Comment by fennecdjay** [comment]
Glad we're done now :smile:
