### ISSUE TITLE
Add documention on "commit convention"

### ISSUE THREAD

**Issue by kylemh** [all-contributors/all-contributors#282]
**Is your feature request related to a problem? Please describe.**
I just used the CLI to initialize all-contributors for my project, but came up on the commit convention question... and I have no idea what this is describing. I went to all the markdown documents, but none of them follow any sort of spec - they all differ quite a bit. I'd love to know more about what I'm dictating for my repository with this answer.

**Describe the solution you'd like**
Subtitles in the CLI or a link to documentation in this repo about how I am supposed to decide beyond reading the multiple, multi-thousand word READMEs.

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/all-contributors/all-contributors/pull/258

**Comment by Berkmann18** [comment]
Have you checked this [documentation page (CLI configuration)](https://allcontributors.org/docs/en/cli/configuration)?

> I went to all the markdown documents, but none of them follow any sort of spec - they all differ quite a bit.

Mind expanding on that?

> Subtitles in the CLI or a link to documentation in this repo about how I am supposed to decide beyond reading the multiple, multi-thousand word READMEs.

The [README.md](https://github.com/all-contributors/all-contributors/blob/master/README.md) of this repo does have a link to the official documentation:
> ## Specification
> The [specification](https://allcontributors.org) is detailed on [allcontributors.org](https://allcontributors.org)

Same goes for the [CLI's README.md](https://github.com/all-contributors/all-contributors-cli/blob/master/README.md):
>## Using the all-contributors-cli

> If you're looking to use the cli, head over to [the cli docs on allcontributors.org](https://allcontributors.org/docs/en/cli/overview). The all-contributors website contains all the information required to install, configure and use the all-contributors-cli.

**Comment by kylemh** [comment]
I see it now! I guess the hashlinks weren't working from wherever I clicked and I was left scouring the big documents - or it could've been my browser... The links inside the CLI config documentation explained clearly.

**Comment by Berkmann18** [comment]
@kylemh Hmm, that's weird.
I'm glad that the docs explained that new field clearly 😁.
