### ISSUE TITLE
HTML generated respects MD linter rule: MD013 Line length

### ISSUE THREAD

**Issue by taqtiqa-mark** [all-contributors/all-contributors#289]
**Is your feature request related to a problem? Please describe.**
The HTML inserted into Readme.md breaks Md linter.

**Describe the solution you'd like**
Inserted HTML code have width < 80 chars.

**Describe alternatives you've considered**
Inserted code warns not to altered generated code.

**Additional context**
This is the only thing breaking the linting check in my Circle-CI orb
```
#!/bin/bash -eo pipefail
mdl ./
.//README.md:191: MD013 Line length

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
Exited with code 1
```

**Comment by Berkmann18** [comment]
Hi @taqtiqa-mark, a [PR on the CLI repo](https://github.com/all-contributors/all-contributors-cli/pull/194) just got merged and it addresses this issue.
Could you please try `all-contributors-cli@^6.8.0` and see if it resolves your issue?
