### ISSUE TITLE
Custom types not working

### ISSUE THREAD

**Issue by naturecodevoid** [all-contributors/all-contributors#290]
**Describe the bug**
I copied the custom types code snippet from [here](https://allcontributors.org/docs/en/bot/configuration) and I can't get it to work. When I ask it to add 'custom', it says that is not valid. 

**To Reproduce**
1. Go to https://allcontributors.org/docs/en/bot/configuration and copy the custom types snippet at the bottom into your .allcontributorsrc file
2. Open a random issue or use the CLI to try to add yourself as a contributor for custom
3. If you used the bot, make a comment asking the bot to add yourself as a contributor for custom

**Expected behavior**
You will be added as a contributor with the special emoji and type

**Screenshots**
![94DA8481-FC7A-40F7-A6FC-C6FD25C01FB9](https://user-images.githubusercontent.com/44983869/61383365-60286700-a863-11e9-8e97-5da74c7b1f69.png)

**Comment by jakebolam** [comment]
It is not currently working, you are correct. 

PRs welcome to support this!

**Comment by Bryzizzle** [comment]
It seems that this Bug has been first seen more than a year ago. Is it not fixed yet? Is there a workaround?

**Comment by Berkmann18** [comment]
AFAIK no one submitted a PR for this and some us have been quite busy.

**Comment by tenshiAMD** [comment]
Checkout https://github.com/all-contributors/cli/issues/321. Closing this for now.
