### ISSUE TITLE
The bot @all-contributors require a capitalized README.md file name

### ISSUE THREAD

**Issue by dance2die** [all-contributors/all-contributors#298]
**Describe the bug**

The bot @all-contributors require a capitalized README.md file name

When you go to the following issue, https://github.com/dance2die/sung/issues/1, the bot reports that 

> @dance2die
> File README.md was not found in the repository (undefined).

**To Reproduce**
1. Go to https://github.com/dance2die/sung/issues
2. Add a message `@all-contributors please add @dance2die for code and content`
3. Wait for the error message from the bot.

**Expected behavior**

The bot should not care the capitalization of README.md file but ignore cases.

**Screenshots**

![error](https://user-images.githubusercontent.com/8465237/61999688-c481cc80-b094-11e9-9c02-d1155af786f7.png)

**Additional context**

Reported first on the slack channel.

![slack](https://user-images.githubusercontent.com/8465237/61999722-4eca3080-b095-11e9-91f3-37e348a5ea2c.png)

**Comment by Berkmann18** [comment]
Seems like it's due to the default config using `README.md`.
The web-app integration for the bot would help with scenarios like this.

**Comment by tenshiAMD** [comment]
@dance2die all you need to do is define the config file. Please check the latest documentation. Closing this for now. Thanks!
