### ISSUE TITLE
Question: template for more than contributions

### ISSUE THREAD

**Issue by adswa** [all-contributors/all-contributors#301]
If I read the [docs on configuration](https://allcontributors.org/docs/en/bot/configuration) correctly, it is possible to define custom contribution types. Is it also possible to add fields other than "contributions", such as affiliation and orcid? 

The background to this is that it would make it possible to potentially automate the creation of a ``.zenodo.json`` file from the information the bot collects.

I'm envisioning the end result in .all-contributorsrc could look something like this

```
    {
      "login": "adswa",
      "name": "Adina Wagner",
      "avatar_url": "https://avatars1.githubusercontent.com/u/29738718?v=4",
      "profile": "https://www.researchgate.net/profile/Adina_Wagner",
      "affiliation": "Institute of Neuroscience and Medicine, Brain & Behaviour (INM-7), Research Centre Jülich, Jülich, Germany",
      "orcid": "0000-0003-2917-3450",
      "contributions": [
        "code",
        [...]
      ]
    },
```

and the call to the bot something like this:

```
@all-contributors please add @adswa for code, ideas, example with orcid "0000-0003-2917-3450" and affiliation  "Institute of Neuroscience and Medicine, Brain & Behaviour (INM-7), Research Centre Jülich, Jülich, Germany".
```

Is an extended configuration like this possible?

Thanks a lot in advance!

**Comment by Berkmann18** [comment]
At the moment, it's not possible to do that.
@all-contributors/core What do you all think about this?

**Comment by gr2m** [comment]
I think it's out of scope, but maybe you can find a workaround for your case?

**Comment by adswa** [comment]
Thanks a lot for the quick response to this! Please feel free to close the issue.

**Comment by yarikoptic** [comment]
Ha, I searched for orcid in this repo and found you @adswa ;-) workaround could probably be done by finding GitHub logins on orcid - it allows for linking GitHub id into your orcid record, and then querrying all desired fields from it. Additional integration should be preparing . zenodo.json records. But indeed it would've been awesome if all-contributors supported that natively.

**Comment by Berkmann18** [comment]
@yarikoptic To be fair, an extension or 3rd-party plugin or tool would be welcome.
