### ISSUE TITLE
Badge link does not work

### ISSUE THREAD

**Issue by marekrozmus** [all-contributors/all-contributors#304]
The badge link is missing '-' at the end. Currently it is '#contributors' and should be '#contributors-' because of the emoji used in contributors header.

**Comment by Berkmann18** [comment]
@marekrozmus Where?

If it's in one of your repos, make sure to update `all-contributors-cli` and run `all-contributors generate` (unless you're using the bot).

**Comment by marekrozmus** [comment]
I'm using the bot.

**Comment by Berkmann18** [comment]
@marekrozmus Try to get the bot to add an empty contribution and it should update the table.

**Comment by marekrozmus** [comment]
Maybe I'll try to provide more details. The problem is that generated link for contributors badge is not working.
You can check this [example repository](https://github.com/marekrozmus/all-contributors-test) and try to click the "all contributors" badge.

Bot creates following link:
`https://github.com/marekrozmus/all-contributors-test#contributors`
and it should be:
`https://github.com/marekrozmus/all-contributors-test#contributors-`

**Comment by jakebolam** [comment]
This has since been updated. Thank you for reporting.

https://github.com/all-contributors/all-contributors-cli/blob/master/src/init/init-content.js#L6
