### ISSUE TITLE
Contribution type for correcting typos

### ISSUE THREAD

**Issue by simskij** [all-contributors/all-contributors#307]
First and foremost, thank you for all the amazing work. This project has really helped in improving the visibility of contributions to open source projects. 🙏 

**Is your feature request related to a problem? Please describe.**
It's quite common, at least for my projects, to get drive-by contributions fixing just a random typo in either one of the application strings or in the documentation. Currently, at least in my opinion, there's no suitable category to put these contributions in. Adding it as code or documentation seems unfair to other contributors with more substantial contributions.

**Describe the solution you'd like**
Adding a new category, proofreading or copy, especially for covering this contribution type. 
A suiting emoji in the emoji key could be 🤓 or 🧐.

**Describe alternatives you've considered**
I've really tried to convince myself that it would fit in one of the existing categories, but it doesn't really feel right. The closest one i've found is  `🖋 content`, but even that feels forced.

**Comment by Berkmann18** [comment]
You raise some good points.
The thing with the AC specification is that it's there to recognise any contributions regardless of its impact while attributing it the correct contribution type.

It's true that there might be some contributions that can't fit well in any of the categories.
I've also seen people aiming for some representations that go deeper into what each contributor did (that could be considered if there's enough interest).

Regarding the fairness of having two contributions classified as say `code` where one is substantial (e.g. adding a feature) and the other minor (e.g. fixing a typo) then I'll suggest the following things:
- Adding listing rules, say each contribution are sorted by category then by their impact.
- Adding the `name-your-contributors` list sorted by contributions.
- Adding information to the AC table that indicates the impact/weight of each contribution (e.g. @MatheusRV' suggestion on #233).

The problem with _correcting typos_ is that it's ambiguous and could be either translation, documentation, code, design or even content/blog/maintenance.

**Comment by Berkmann18** [comment]
Friendly ping @simskij.

**Comment by simskij** [comment]
I'm not that keen on adding complexity to the AC table. One of the main benefits of this project, other than the core value proposition, is that it's extremely accessible and easy to use.

As I do agree with your stance on ambiguity, I've just used code or docs for now. I still don't really like it, but at least it lets you recognize people's effort without having to customize anything.

With that said, feel free to close the issue unless you want to continue exploring options as I currently don't have any other, low-effort, suggestions. 😅 

Thanks again!

**Comment by Berkmann18** [comment]
That makes sense, have you tried incorporating `name-your-contributors`?
