### ISSUE TITLE
Make the bot resolve a conflic with multiple PRs

### ISSUE THREAD

**Issue by Andre601** [all-contributors/all-contributors#310]
**Is your feature request related to a problem? Please describe.**
When you add multiple contributors through multiple PRs does the bot create one for each contributor.
This can and will cause conflicts, especially when a .all-contributorsrc doesn't exist yet and would be added through the PRs.

**Describe the solution you'd like**
When there are multiple PRs should the bot auto-update its commits when other PRs are merged that contain changes to the targeted files.

Example:
I add User1 to the contributor-list for code and the bot creates a PR. I then add user2 for bug report and the bot creates a second PR.
Now I merge the first PR, which will cause conflicts to the second one. Now the bot will update their commit to update the PR, fixing the conflict.

**Describe alternatives you've considered**
Resolving the issue manually, which would be a bit more difficult.

**Additional context**

-

**Comment by Berkmann18** [comment]
I believe with additions from https://github.com/all-contributors/all-contributors-bot/pull/127. There's an existing issue (https://github.com/all-contributors/all-contributors-bot/issues/146) around this as well (not sure if the other folks made any progress).

**Comment by samajammin** [comment]
This would be great! I hit this same issue after opening PRs for ~70 contributors 😅. I think a bulk add feature (https://github.com/all-contributors/all-contributors-bot/issues/100 & https://github.com/all-contributors/all-contributors-bot/issues/146) or ability to backfill contributors (https://github.com/all-contributors/all-contributors/issues/311) would also alleviate this issue.

**Comment by Berkmann18** [comment]
@samajammin AFAIK, @jakebolam hasn't finished working on the bulk add functionality.
Normally you should be able to use the CLI's `fetch` experimental feature (I haven't had the time to fix issues blocking the progress on that side) and that should help.

**Comment by Andre601** [comment]
I will move this to https://github.com/all-contributors/all-contributors-bot as it is more about the bot than this repository in general.
If it actually is, feel free to re-open it (or let me know so that I can re-open it).
