### ISSUE TITLE
Add option to directly add all contributors with reason "code"

### ISSUE THREAD

**Issue by Andre601** [all-contributors/all-contributors#311]
[contributors]: https://github.com/all-contributors/all-contributors/graphs/contributors

**Is your feature request related to a problem? Please describe.**
*No issue*

**Describe the solution you'd like**
It would be cool to have an option to let the all-contributors bot add all people that contributed to the repository with PRs (Have the "contributors" label next to their name in issues/PRs and are shown in the [contributors] page).

The command could be something like `@all-contributors please add all contributors` and the bot would make a PR containing everyone listed in the contributors tab.

**Describe alternatives you've considered**
The only alternative would be to manually add them one by one, which not only is slow, but also can cause conflicts when multiple PRs are made at the same time without merging others first (see #310 for context)

**Additional context**

**Comment by Berkmann18** [comment]
This would be cool indeed, there's a complementary feature (still a WIP) on the CLI which would enable it (and by extension the bot as well which some additional changes) to automatically add contributors.
Feel free to contribute/help if you want.

**Comment by samajammin** [comment]
Came here to suggest this feature! Would be great if there was an ability to backfill all project contributors without having to do it manually one by one. Awesome project overall!

**Comment by Berkmann18** [comment]
@samajammin That's what https://github.com/all-contributors/all-contributors-cli/pull/196 is aiming to solve but as I've mentioned across the board, I didn't manage to fix some blocking issues (and I haven't had the time to look into it lately).
If you want to help, then please do.

**Comment by Andre601** [comment]
I close this issue as it already exists as PR (See above comment) and to move to the actual right repository for this stuff...
