### ISSUE TITLE
Adding "data" emoji for collected data

### ISSUE THREAD

**Issue by smoia** [all-contributors/all-contributors#334]
**Is your feature request related to a problem? Please describe.**
I discovered all-contributors thanks to [tedana](https://github.com/ME-ICA/tedana), a package for neuroimaging data analysis. I'm trying to implement it for [phys2bids](https://github.com/smoia/phys2bids), another package for neuroimaging related data handling.
I hope this is not too similar to #63 , but the thing is that "content" as specified now doesn't seem to cover those people who collect data and contribute to a project in that way.
Also, it might be useful to distinguish between data _for testing_ and data for "consumption".

**Describe the solution you'd like**
It would be nice to either update the definition of "content" contributors, or to add a new entry for "data" contributor (that doesn't seem too bounded to text production).

**Describe alternatives you've considered**

**Additional context**
It would even be better to have two entries, one for generic "data" and one for "data for tests".

**Comment by Berkmann18** [comment]
I see where you're coming from.
What description for `content` would you rather see? (PR welcome).

**Comment by smoia** [comment]
It's not necessary to change the description of `content` that there is now, I think it's useful to have an entry like that for websites or app development and maintenance project. What I'm suggesting is a different entry for data handling projects (visualisation, analysis, preprocessing, ...) that need to have data for testing, or projects with data collection or classification (creation/update of databases, manual labellings etc.) to show a different kind of contribution.
If there's agreement about it, I can start a PR!

**Comment by Berkmann18** [comment]
:symbols: seems representative of that.
And I see value in this new type.

@all-contributors/core What do y'all think?

**Comment by smoia** [comment]
@Berkmann18 I can work on a PR in the upcoming days!

**Comment by Berkmann18** [comment]
@smoia That would be amazing (don't forget there are 3 repos to update for changes like this ;)).

**Comment by smoia** [comment]
@Berkmann18 what do you mean? I was checking your PRs for Project Manager, and I saw that you changed 3 files. Are there more repositories instead?

**Comment by smoia** [comment]
@Berkmann18 Ok, I just noticed it. I'm going to use your project manager PRs (e.g. #141 ) as a model .

**Comment by smoia** [comment]
@Berkmann18 sorry to bother you, but I'm trying to add the emojis in the files. I'm typing it in, but that's not enough? How do you add the emoji inside the md file other than :code: ?

**Comment by Berkmann18** [comment]
@smoia You may need to copy-paste it from GH or any place that have the emoji icon.

**Comment by smoia** [comment]
I did - still getting the expression itself rather than the emoji.
Might be editor related. Which one did you use?

**Comment by smoia** [comment]
@Berkmann18 managed! I had to manually enter the unicode equivalent.
First PR ready!

**Comment by smoia** [comment]
Second PR ready - should I wait for a new tag/release of all-contributors before modifying the all-contributors-bot?

**Comment by Berkmann18** [comment]
I'm glad to see that you managed to do it.
Since the bot relies on the CLI, it would be **better** to make sure the bot uses the latest version of the CLI.
That being said, you could always apply the relevant changes, submit a *draft* PR and once the new CLI release is out you could add the version update in your bot PR.

That way, you already have the core of the bot PR ready to reviewed (even tho GH disables reviews for draft PRs) without having to wait.

**Comment by smoia** [comment]
Oh ok, I see.
Should I re-open the PR as draft?
Also for the bot, don't I have to wait for a new release of all-contributors (I can open a draft in the meantime).

**Comment by Berkmann18** [comment]
@smoia For the CLI/spec repo, no need.

> Also for the bot, don't I have to wait for a new release of all-contributors (I can open a draft in the meantime).

You could wait, however, I think it would be better to already have a (draft) PR submitted so you just need to commit the version change. Alternatively, you can set it up locally and push the PR once the release comes in.

**Comment by smoia** [comment]
@Berkmann18 last PR ready, tested and corrected. After that, I'd say we close this issue!

**Comment by Berkmann18** [comment]
@smoia It won't pick it up when you tell it to add a _data_ contribution (unless you mean the test bot you set up with your changes) until the code pushed.
However, it should be fine for the table generation bit as the bot uses the CLI for this.

**Comment by smoia** [comment]
I see - yes, obviously the code has to be merged first. I'll wait and see!
