### ISSUE TITLE
Merging bot PR right after normal PR can break semantic-release

### ISSUE THREAD

**Issue by MichaelDeBoey** [all-contributors/all-contributors#338]
Right after merging MichaelDeBoey/gatsby-remark-embedder#43, I added @cms to the contributors list.
When merging MichaelDeBoey/gatsby-remark-embedder#45 too, [this skipped releasing (using `semantic-release`)](https://travis-ci.org/MichaelDeBoey/gatsby-remark-embedder/jobs/622120699#L542) on the first merge commit (which is expected).
The only problem is that the second merge commit didn't trigger CI anymore (due to it's `[skip-ci]` text), so I had to do a [manually release](https://github.com/MichaelDeBoey/gatsby-remark-embedder/commit/607183716fca1ad80688b5f2b7ede51dfb11c4ac) of [`gatsby-remark-embedder@1.6.0`](https://github.com/MichaelDeBoey/gatsby-remark-embedder/releases/tag/v1.6.0).

A solution for this annoyance could be to wait until the release happened before I add contributors to the list, but that's equally annoying imo.

Can't really think of a solution to fix this, 'cause I like the fact CI is skipped on the docs PRs tbh. 😕

**Comment by Berkmann18** [comment]
So if I understood properly, the all-contributors commits were mixed with the CI-relevant ones (read the ones that _should_ trigger the CI)?

**Comment by MichaelDeBoey** [comment]
No they aren't.

I first had PR MichaelDeBoey/gatsby-remark-embedder#43, which I squashed +merged.
This triggered CI (which runs `semantic-release`), like was expected.

Right after that, I run the all-contributors bot, which created MichaelDeBoey/gatsby-remark-embedder#45.
Since CI is now skipped (I love that!), I could immediately squash + merge it too.

Merging MichaelDeBoey/gatsby-remark-embedder#45 had the implication that the `semantic-release` run of MichaelDeBoey/gatsby-remark-embedder#43's CI didn't publish that commit.
https://travis-ci.org/MichaelDeBoey/gatsby-remark-embedder/jobs/622120699#L542

This was expected too.
The only annoying thing is that the merge of MichaelDeBoey/gatsby-remark-embedder#45 didn't trigger a new CI run, because of the `[skip-ci]` in the body of that squashed commit.

So a solution to my problem would be to wait until MichaelDeBoey/gatsby-remark-embedder#43 was published and only then merge MichaelDeBoey/gatsby-remark-embedder#43.
But if CI takes a long time to publish, that means I have to keep track of that, which is annoying too.

Another solution is to manually release each time (like I did in MichaelDeBoey/gatsby-remark-embedder@6071837), but that's annoying too.

Like I said: I can't really think about another solution to my problem, but just wanted too let you guys know this can be something annoying people are experiencing and could maybe fixed in some way by the bot (even tho I don't know how)?

**Comment by Berkmann18** [comment]
One way would be to turn off the `skipCi` configuration but that might be tricky when using the bot and not a nice solution.
Not sure, how that could be fixed on the bot tho.

**Comment by MichaelDeBoey** [comment]
Not sure either 😕

**Comment by Berkmann18** [comment]
@all-contributors/core Any ideas?

**Comment by Berkmann18** [comment]
@MichaelDeBoey Does the bot's PRs still cause issues in that scenario? With or without `skipCi` set.

**Comment by tenshiAMD** [comment]
@MichaelDeBoey is this still an issue today? Closing this for now. Feel free to open an issue if this still occurs.
