### ISSUE TITLE
Navigated html page not showed in the preview url

### ISSUE THREAD

**Issue by Snickdx** [all-contributors/all-contributors#342]
**Describe the bug**
The current page is not shown in the preview browser url. Works if the browser is popped out in a separate window though.

**To Reproduce**
1. Create any vanilla html multi page project.
2. Click a link from one page to another.

**Expected behavior**
When navigated to another page, the file should show in the url.

**Screenshots**
![ezgif-6-bed5f4fd51b5](https://user-images.githubusercontent.com/5845054/71429043-f5454c80-269a-11ea-8fa3-161d8a538bbd.gif)

**Additional context**

**Comment by Berkmann18** [comment]
Either you posted the issue in the wrong place or posted the wrong thing.
Anyway, this is clearly not related to AC.
