### ISSUE TITLE
Docs clarification: What is the default sort order?

### ISSUE THREAD

**Issue by atuttle** [all-contributors/all-contributors#368]
**Describe the bug**
The documentation for both [the bot](https://allcontributors.org/docs/en/bot/configuration) and [the cli](https://allcontributors.org/docs/en/cli/configuration) clearly lists that it's possible to sort contributors alphabetically, but that the default is `false`. It doesn't say how they will be sorted when set to `false`. Presumably the chronological order in which they were added?

**To Reproduce**
1. Read the docs
2. Be unsure of what will occur with the defaults

**Expected behavior**
The docs should explain the default behavior.

**Screenshots**

cli:
![image](https://user-images.githubusercontent.com/46990/75349582-10873080-5873-11ea-9d28-9661cfa03c1c.png)

bot:
![image](https://user-images.githubusercontent.com/46990/75349609-1c72f280-5873-11ea-812e-e0cda3f35bbb.png)

**Comment by Berkmann18** [comment]
They won't be sorted by default (unless you consider ordered-by-insertion a type of sort).

**Comment by atuttle** [comment]
Sure, I can do that.
