### ISSUE TITLE
Translate README.md to Hindi also

### ISSUE THREAD

**Issue by sk1122** [all-contributors/all-contributors#372]
I want to translate the README.md to Hindi for Indian Viewers.

**Comment by Berkmann18** [comment]
Hi @sk1122, thanks for showing interest in this repo.
I just activated Hindi on https://crowdin.com/project/all-contributors.
Please read https://allcontributors.org/docs/en/project/contribute#translations and get started, if you have any issues please feel free to re-open this issue or comment on #143.
Thank you in advance.
