### ISSUE TITLE
Add multiple people in one command

### ISSUE THREAD

**Issue by shawndwells** [all-contributors/all-contributors#375]
Currently, only one individual can be added at a time, eg

``<bot> add <person>``

But sometimes multiple people work on things together. Could the syntax be updated to allow for adding multiple simultaneously? For example:

``<bot> add @person1, @person2 for <thing>``

**Comment by Berkmann18** [comment]
This should be in issue section of the github.com/all-contributors/all-contributors-bot repo.
It's also a WIP by @jakebolam (cf. https://github.com/all-contributors/all-contributors-bot/pull/127).

**Comment by tenshiAMD** [comment]
PR https://github.com/all-contributors/app/pull/127 is almost done. Closing this one for now.

**Comment by lwasser** [comment]
hi colleagues. does this feature work? i haven't been able to get it to work as of yet.
Many thanks,

**Comment by sherlyfebrianti96** [comment]
Me too, doesn't work.

**Comment by Drakogangcom** [comment]
[Uploading Discover-the-Power-of-Bitly.pdf…]()

**Comment by aleesteele** [comment]
Unfortunately, we're having the same problem as well in our community!
