### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by paras-jain** [all-contributors/all-contributors#376]
Hey, I noticed that Romanian translations were complete and ripe for addition to site. While looking for the documentation for doing the same using crowdin CLI, I found that the following two links are broken:
- https://github.com/all-contributors/all-contributors/blob/master/docs/tooling
- https://github.com/all-contributors/all-contributors/blob/master/docs/repository-maintainers

Also can only maintainers make additions to the site?

**Comment by gnclmorais** [comment]
Where did you see those links, @paras-jain? They seem to work by adding `.md` at the end:
- https://github.com/all-contributors/all-contributors/blob/master/docs/tooling.md
- https://github.com/all-contributors/all-contributors/blob/master/docs/repository-maintainers.md

**Comment by paras-jain** [comment]
@gnclmorais in  [all-contributors/docs/emoji-key.md](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md)
I inspected the emoji-key markdown, the links are wrong. Will submit a PR for the same.

**Comment by paras-jain** [comment]
Submitted a PR, please review.

**Comment by Berkmann18** [comment]
Hi,
I just ran a broken link check and none of the 2 pages seems to have came up.

I just checked on the website and those 2 links aren't broken and I suppose appending `.md` would fix them on GitHub but it will break the documentation section of the website so not a desirable solution (I may be wrong tho).

> Submitted a PR, please review.

Make sure, you link the issue to the PR so we can see which one is linked to what.

Thanks.

**Comment by Berkmann18** [comment]
@paras-jain Are the links still broken?

**Comment by paras-jain** [comment]
Yes, have to manually add .md

**Comment by Berkmann18** [comment]
Are you using the [website](https://allcontributors.org/) or using the repo's docs?

**Comment by paras-jain** [comment]
Repository's docs

**Comment by Berkmann18** [comment]
@paras-jain _Genuine question_, what advantage does using this repo for docs over the website that results from it?

**Comment by paras-jain** [comment]
Absolutely none, just wanted to bring to your notice and find whether it can be solved.

**Comment by Berkmann18** [comment]
Ah okay, it's good to know at least about such differences tho.
As I said, it could be resolved but that would be at the detriment of the website.
