### ISSUE TITLE
Cannot read property 'then' of null

### ISSUE THREAD

**Issue by bnb** [all-contributors/all-contributors#378]
**Describe the bug**
Seems that the CLI is currently returning `Cannot read property 'then' of null` on first run in a fresh project.

**To Reproduce**
- run all-contributors init with the following values:
```
? What's the name of the repository? examples
? Who is the owner of the repository? nodejs
? What is the repository type? GitHub
? Where is the repository hosted? Hit Enter if it's on GitHub or GitLab https://github.com
? In which file should contributors be listed? README.md
? Do you want a badge tallying the number of contributors? No
? How big should the avatars be? (in px) 100
? Do you want this badge to auto-commit when contributors are added? No
? What commit convention would you want it to use? None
```

**EDIT:** Move the .all-contributors config to a parent directory.

- run `all-contributors add`
  - the following will result: `? What is the contributor's null username? `
- enter the following values:
```
$ all-contributors add    
? What is the contributor's null username? bnb
? What are the contribution types? 💻  Code, 📖  Documentation, 💡  Examples, ⚠️  Tests
```

This will result in logging `Cannot read property 'then' of null` which prevents the tool from adding a contributor.

Alternatively, running:
```
all-contributors add bnb code
```
Returns the same error.

**Expected behavior**
No error and for the CLI to write as it seems like it's supposed to.

**Screenshots**
![image](https://user-images.githubusercontent.com/502396/78196500-9852f280-7450-11ea-8108-5f6dddf4aa1f.png)

**Comment by bnb** [comment]
I am very extra, I figured it out. I initiated in the incorrect directory and moved the file to the correct one but continued running the commands in the incorrect directory 🤦‍♂

**Comment by Berkmann18** [comment]
@bnb So did you managed to get it to work?

**Comment by bnb** [comment]
I did indeed.
