### ISSUE TITLE
Contributions regarding repo cleanups

### ISSUE THREAD

**Issue by Abdirahiim** [all-contributors/all-contributors#379]
There is currently a user who cleaned up my repo by deleting build artifacts and correcting the gitignore file, so I was wondering if you could add a cleanup emoji key to the bot

**Comment by Berkmann18** [comment]
That's an interesting idea; I think :construction: (maintenance) covers that kind of contribution reasonably well (since cleaning things is a maintenance task, to me at least).

**Comment by Berkmann18** [comment]
@Abdirahiim No, have a look at https://github.com/all-contributors/all-contributors-cli/issues/111#issue-369135884 (tl;dr: it's for anyone who helps in maintaining a repo/project).

**Comment by Abdirahiim** [comment]
I didn’t know that, Thanks

**Comment by Berkmann18** [comment]
No problem :).
