### ISSUE TITLE
"Enter the @all-contributors bot" exactly where?

### ISSUE THREAD

**Issue by hernanmd** [all-contributors/all-contributors#380]
**Is your feature request related to a problem? Please describe.**

Reading "Enter the @all-contributors bot" from the [overview page](https://allcontributors.org/docs/en/bot/overview) does not make it clear exactly where I should "enter" this command (assuming "@all-contributors bot" is the full command).

For people which never used GitHub bots isn't that obvious. Should I create a new issue and type "@all-contributors bot" in the title? Should I leave the title empty and enter it in the body?

**Describe the solution you'd like**

Some clarification on the very start to create the contributors table for an existing projects with some contributors (without having to add each individually)

**Describe alternatives you've considered**

I tried opening a new issue in a project but nothing happened.

**Comment by baikho** [comment]
I think the bot doesn't get triggered when you create an issue immediately mentioning the bot. I've tried this and it appears that the bot mention needs to be done in a pre-existing PR / Issue for it to work, but I may be wrong.

**Comment by Berkmann18** [comment]
@baikho Correct, it only reacts to comments.

**Comment by Berkmann18** [comment]
Friendly ping @hernanmd.

**Comment by hernanmd** [comment]
Yes, thank you for your answer @Berkmann18
