### ISSUE TITLE
Badge question

### ISSUE THREAD

**Issue by thatrobotdev** [all-contributors/all-contributors#390]
Hello!

Would moving the badge to one line like this https://github.com/P2PHackClub/PixTools/pull/15 mess up the 

`<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->`

and

`<!-- ALL-CONTRIBUTORS-BADGE:END --> `

?

It isn't very clear on in the FAQ: [https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update](https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update)

**Comment by Berkmann18** [comment]
As long as the badge is kept within those two comments, it should be fine.

**Comment by thatrobotdev** [comment]
Awesome, thanks @Berkmann18!

**Comment by Berkmann18** [comment]
No problem.
