### ISSUE TITLE
stop package-lock.json from generating

### ISSUE THREAD

**Issue by NotMoni** [all-contributors/all-contributors#393]
Since you guys use yarn, you don't need a pkg-lock.json

**Comment by NotMoni** [comment]
I will make a PR to fix this.

**Comment by Berkmann18** [comment]
There's no `package-lock.json` on our repos or let alone this one.

**Comment by NotMoni** [comment]
@Berkmann18 take a look at my pr. 🦄

**Comment by Berkmann18** [comment]
Do you realise that this is the general/documentation/website repo right?
So any NPM related configuration doesn't have any place here, on the CLI repo, sure.
If you want to contribute without accidentally pushing a `package-lock.json` then it should be added to `.gitignore`.

**Comment by NotMoni** [comment]
alright

**Comment by NotMoni** [comment]
@Berkmann18 Check PR #395
