### ISSUE TITLE
Avatar size 

### ISSUE THREAD

**Issue by pavelloz** [all-contributors/all-contributors#409]
**Is your feature request related to a problem? Please describe.**
There is a config setting:
```
  "imageSize": 100,
```

Which means while generating, script knows what size image will be, exactly.

**Describe the solution you'd like**
I would like to see `&s=${size}` added to the avatar_url

**Describe alternatives you've considered**

**Additional context**
Example commit optimizing it: https://github.com/mdyd-dev/nearme-documentation/commit/dd80f79280d6d551521b88e32fc4a0ff1cd93c96

Single avatar with default size was ~22-25KB
After optimization to 100px because this is what our config looks like, it went down to 4-6KB per avatar. This is pretty substantial.

Some comparison of how much can be gained:

**all-contributors**
<details>

![image](https://user-images.githubusercontent.com/546845/84124499-96527480-aa3b-11ea-8f58-bc0d3633f017.png)

</details>

**nearme-documentation**
<details>

![image](https://user-images.githubusercontent.com/546845/84124581-b71aca00-aa3b-11ea-805f-831cd3407aaa.png)

</details>

In this commit I also changed avatarsX. subdomain to 0 (GH by default uses round robin or something) to avoid multiple SSL handshakes (which further speeds up load time), but the most important thing that i want to signalize here is the image size.

Good job on the project (and the bot :) )!

**Comment by Berkmann18** [comment]
That looks great, a PR would be appreciated!
