### ISSUE TITLE
Username with hyphens not accurately identified

### ISSUE THREAD

**Issue by b-zurg** [all-contributors/all-contributors#413]
**Describe the bug**

**To Reproduce**
Add bot comment such as `@all-contributors please add b-zurg for test doc code design example platform`

A PR for the user `b` is created.

**Expected behavior**
A PR for the correct user `b-zurg` should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/57298613/85123577-290bc400-b231-11ea-86cd-ad4342c91ea5.png)

**Comment by Berkmann18** [comment]
Make sure to write the comment where the `@` precedes the username as shown on https://allcontributors.org/docs/en/bot/usage.

**Comment by b-zurg** [comment]
Ah yup that did it. The documentation might mention the format a little bit more clearly but it works well once I did it. It's surprising it worked at all without the @

**Comment by Berkmann18** [comment]
@b-zurg The bot used to support both but that lead to issues so the only reliable way is to at people.
If you have any suggestions to improve the docs, feel free to do so.
