### ISSUE TITLE
Add emoji for mentoring/onboarding

### ISSUE THREAD

**Issue by mloning** [all-contributors/all-contributors#423]
**Is your feature request related to a problem? Please describe.**
Helping new contributors on the way to their first contribution is a lot of work and usually not reflected in direct code contributions, but none of the current emojis really capture this aspect. 

**Describe the solution you'd like**
An emoji in the emoji key for mentoring/onboarding. 

**Describe alternatives you've considered**
None of the available emojis in the [emoji key](https://allcontributors.org/docs/en/emoji-key) captures this well I think. "Review" comes closest to it.

**Comment by Berkmann18** [comment]
That's an interesting one which I think would be valuable to add.
What emoji do you think would be appropriate for that?

**Comment by mloning** [comment]
I was thinking about this too and couldn't come up with a good one, I'll take another look at the available emojis!

**Comment by mloning** [comment]
Options: 
* :busts_in_silhouette:
* :two_women_holding_hands: (but I don't like that it's gendered, should just be two persons holding hands)
* :school: (school)
* :beginner: (it's called beginner, but don't understand the symbol)
* :school_satchel: (school satchel)
* :teacher: (teacher)

**Comment by Berkmann18** [comment]
Yeah, we should avoid the gendered ones, I like the first one, I can't seem to find the code for it.

> :beginner: (it's called beginner, but don't understand the symbol)

I guess it's because it's a book or at least looks like one but yes, it's not that obvious.

The :teacher: one is weird because it seems gendered but GH shows a fairly different (not a merge) version compared to :man_teacher: and :woman_teacher:.

I quite like the :school: and :school_satchel:.

cc @all-contributors/core

**Comment by gr2m** [comment]
@Berkmann18 👥 is `:busts_in_silhouette:`

I think when you know the context, then 👥 is pretty good. But I think the teacher emoji will be more clear when seen among the other emojis in READMEs.

# :busts_in_silhouette:
# :teacher:

**Comment by mloning** [comment]
+1 for 🧑‍🏫

**Comment by Berkmann18** [comment]
@gr2m I agree.
I'll also vote for :teacher:

**Comment by mloning** [comment]
On the GitHub app on my phone :teacher: actually looks like two emojis: a person and the school building ...

**Comment by mloning** [comment]
Should I open a PR to add this into the emoji key file here: https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md?

**Comment by gr2m** [comment]
yeah let's do that
