### ISSUE TITLE
Please Change "Português" to "Português do Brasil"

### ISSUE THREAD

**Issue by MM-coder** [all-contributors/all-contributors#428]
Hello,

I have noticed that in the README the Brazilian Portuguese language translation is marked as Portuguese. Linguistically speaking this is incorrect as Brazilian Portuguese is merely a dialect of Portuguese and not an independent language. It has different grammar and has a few additional words.

I'd be willing to pull-request this here and on the website if needed.

Cheers

Mauro M.

**Comment by TotallyNotCallum** [comment]
ha gay

**Comment by Berkmann18** [comment]
That's a good point, I wonder if it's worth keeping that section as it was used back when there are as many translated version as there languages on that README and is quite outdated now.
In any case, if it's indeed incorrect then feel free to change it.
