### ISSUE TITLE
Prettier and All Contributors conflicting

### ISSUE THREAD

**Issue by melink14** [all-contributors/all-contributors#441]
**Describe the bug**
Generated all contributors section does not conform to Prettier and can't be worked around.

```
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
```
is formatted by prettier to:
```
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
```

The generator adds `prettier-ignore` comments around the table but since it ends before the `ALL-CONTRIBUTORS-LIST:END` comment prettier wants to format the final line.

Generally, prettier would recommend putting the `prettier-ignore` comments outside the `ALL-CONTRIBUTORS-LIST` comments but this doesn't work as long as all-contributors-cli is inserting them inside.

Prettier is famously opinionated and has no config for this meaning there's nothing a user of both all contributors and prettier can do to avoid a clash.

**To Reproduce**
1. Run prettier on a file with generated Contributors section.
2. Run `prettier --check` and see that it's not compliant.
3. Run `prettier --fix` to re-format but notice it gets reverted after another generate.

**Additional context**
I'm not sure if this was caused by a recent update but I'm surprised it wasn't noticed previously (maybe I'm missing something). Since we use CI checks to prevent unformatted code from being merged it means we can't use the bot and have to manually edit the output from the CLI.

Thanks!

**Comment by Berkmann18** [comment]
AFAIK, the problem with the code being changed to having a space leading to
```md
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
```
like in the CLI's README.md hasn't been an issue and I suspect no one noticed that until you did (especially with the few issues around `markdownlint`).

At this point, it can fixed on the CLI side (easy [PR but welcome](https://github.com/all-contributors/all-contributors-cli/pull/new)) with a CLI version bump on the bot side.
This way, it wouldn't require manual intervention.

**Comment by melink14** [comment]
Thanks for the reply.

So the suggested fix explicitly is:
- Change CLI to insert prettier compliant newline
- Update required NPM version of the CLI in the bot's package.json.

I can send a PR for the CLI fix though let me know of other ideas. The only other possibilities I can think of are:
- Move lint/formatter ignores outside the ALL-CONTRIBUTORS comments. Works but would be counter intuitive and possibly lead to confusion later on.
- remove the lint/formatter lines and include instructions to users to use them if they need to. This has most flexibility but also could increse support load as people don't realize what they need to do.

**Comment by Berkmann18** [comment]
The suggested fix seems good to me and I suspect removing the lint/formatter lines to cause the linter/formatter issues that lead to them being added in the first place.
