### ISSUE TITLE
Use all-contributors bot on different platforms (Gitlab, Bitbucket)?

### ISSUE THREAD

**Issue by fullstackzach** [all-contributors/all-contributors#443]
**Is your feature request related to a problem? Please describe.**
I am interested in implementing the all-contributors bot on a different platform than Github, like Gitlab. Specifically a self-hosted gitlab instance. Is this possible? It seems like there is only a GitHub app available.

**Describe the solution you'd like**
Be able to create an all-contributors bot instance on my own platform and set it up for use there

**Describe alternatives you've considered**
Based on the installation instructions, It seems like all-contributors supports GitHub only

**Comment by Berkmann18** [comment]
How different are GH apps to GitLab and Bitbucket?
I guess it would be possible to port the bot repo to or add GL/BB support but that's way out of my area.
The CLI itself is agnostic in that regards tho.

**Comment by olekw** [comment]
@Berkmann18 From what I understand, the CLI has a node dependency. It would be nice to just do this in GitLab without the additional dependency.

**Comment by Berkmann18** [comment]
What's preventing you from using it with its existing dependencies?

**Comment by olekw** [comment]
@Berkmann18 I try to have as little extraneous software as possible on my development machine. Therefore being able to use this functionality directly in GitLab would be very helpful.

**Comment by Berkmann18** [comment]
@olekw You can always create a CI/CD pipeline that uses it without having to install it on your machine.

**Comment by tenshiAMD** [comment]
> @olekw You can always create a CI/CD pipeline that uses it without having to install it on your machine.

@olekw you can follow what @Berkmann18 suggestions to you. Closing this for now.
