### ISSUE TITLE
Add a "research" contribution type

### ISSUE THREAD

**Issue by LaChapeliere** [all-contributors/all-contributors#446]
**Is your feature request related to a problem? Please describe.**
I cannot recognise the contribution of some of my teammates because they did research and that doesn't fit into any available type.

**Describe the solution you'd like**
I would like a research type to be added, for people doing literature review or algorithm development for example. Very common type of contribution for academia projects.
The emoji could be :microscope: or something else.

**Additional context**
I'm willing to work on a PR if this is approved.

**Comment by Berkmann18** [comment]
Sounds like a good idea.
PR Welcome!

**Comment by LaChapeliere** [comment]
CLI tool: https://github.com/all-contributors/all-contributors-cli/pull/291

**Comment by LaChapeliere** [comment]
Bot: https://github.com/all-contributors/all-contributors-bot/pull/323

**Comment by LaChapeliere** [comment]
I've created the type following the example of the PRs for the accessibility type, but I'm rather lost on how to test the CLI and bot PRs.

**Comment by Berkmann18** [comment]
There are no contribution-type specific tests, so as long as they render fine and are what was accepted it should be ok.

**Comment by Berkmann18** [comment]
Done in #330
