### ISSUE TITLE
Template/class attribute for `<table>` tag

### ISSUE THREAD

**Issue by klieret** [all-contributors/all-contributors#465]
We want to include the contributors file which is updated by the all-contributors bot in a web page. This is not a problem, because the output is already HTML and we could even configure the template for each contributor. 

However, it's not possible to assign the table itself a class, as in `<table class="authors-table">`, which makes it impossible to configure via CSS.

So it would be nice to either have a config option `tableClass` or to have a `tableTemplate` that can be filled by the bot.

Or is there another workaround possible (other than reading the json file and generating the HTML ourselves)?

**Comment by klieret** [comment]
Ah, actually one workaround would be to enclose the `<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->` blocks in a `div` with classes, like so:

```html
<div class="my-class my-table">
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
</div>
```

I will close this issue, as this should cover every use case, right?

**Comment by Berkmann18** [comment]
It seems that your solution would work although I wonder how that would play out on GitHub when (inline/) CSS is stripped off from the code.

**Comment by klieret** [comment]
Yes, in our case this is for a webpage built from markdown files with Jekyll, it won't have any effect on a github readme or similar as you said.
