### ISSUE TITLE
Add "CrediT" contribution type

### ISSUE THREAD

**Issue by jcolomb** [all-contributors/all-contributors#471]
**extension of contribution type**

Would be nice to add credit terms (http://credit.niso.org/) used in academia as contribution types. One could maybe use the image created at https://github.com/mozillascience/PaperBadger as base for the emojis?

This may be especially interesting for the large amount of non-software projects that have their home on github.

I do not know whether some already exist and the bot could just accept different terms for it, but could dig a bit more if there is interest.

**Comment by Berkmann18** [comment]
I had a quick look at it and noticed that CrediT is a set of contribution categories which include some that already available in All Contributors.
I'm not sure what would be needed that AC doesn't cover.

**Comment by jcolomb** [comment]
1. get the bot to recognize credit term, and add AC contribution if there is a mapping category
2. add categories for credit term one cannot map to AC categories (Resources for example ?)

If there is interest, I would try to do a mapping.

**Comment by Berkmann18** [comment]
I see, I think it may be better as an extension since some of those seems really specific.
@all-contributors/core Any thoughts?
