### ISSUE TITLE
Efficiency Suggestion

### ISSUE THREAD

**Issue by Glitchy-Pixel-Gun-3d-Devs** [all-contributors/all-contributors#481]
I Think that letting users Post NSFW To Train the "AI" of the bot to be more efficient, have less false positives and faster page loading.

Just Put A "Hate False Positives? Want to increase speed of page loading? Here's how you can Help" Button At the bottom Of The UI
![tempsnip](https://user-images.githubusercontent.com/70583367/103458401-806e0f00-4cff-11eb-990b-c22094d7b15c.png)

P.S. Scan The Image Before Processing for viruses/ malware

Thanks

**Comment by Berkmann18** [comment]
That seems unrelated to this project or let alone any All Contributors repos.
Please open it at the right place.
