### ISSUE TITLE
recognizing contributors who are not on GitHub

### ISSUE THREAD

**Issue by rgommers** [all-contributors/all-contributors#508]
**Is your feature request related to a problem? Please describe.**

https://allcontributors.org/ starts with _"Including those that don't push code"_. Many of those people - from funders to designers - do not have a GitHub username. It currently does not seem possible to use either the bot or the CLI to add such contributors.

**Describe the solution you'd like**

Instead of a GitHub username, allow providing a regular name (e.g. in quotes, "Firstname Lastname") and the other fields that make sense, like a link to a personal website. Use a default GitHub avatar.

**Describe alternatives you've considered**

Editing the `.all-contributorsrc` by hand. That's a bit clumsy, and still leaves a question about what to put in the `"login"` field.

**Comment by ccamara** [comment]
Possibly duplicated of #339 ?

**Comment by gr2m** [comment]
I agree with Carlos. Ralf would you mind if we close this issue and continue discussion in #339?
