### ISSUE TITLE
cannot use the bot with a .rst file

### ISSUE THREAD

**Issue by 12rambau** [all-contributors/all-contributors#511]
I use the following json file to pilot he all-contributor bot : 

```json 
{
  "files": [
    "AUTHORS.rst"
  ],
  "imageSize": 100,
  "contributorsPerLine": 7,
  "contributorsSortAlphabetically": false,
  "badgeTemplate":  "<img src=\"https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square\" alt=\"All contributors\">",
  "contributorTemplate": "<a href = \"<%= contributor.profile %>\"><img src=\"<%= contributor.avatar_url %>\" width=\"<%= options.imageSize %>px;\" alt=\"\"/><br /><sub><b><%= contributor.name %></b></sub></a>",
  "skipCi": true,
  "contributors": [
    {
      "login": "12rambau",
      "name": "Rambaud Pierrick",
      "avatar_url": "https://avatars.githubusercontent.com/u/12596392?v=4",
      "profile": "https://12rambau.github.io/web-resume/",
      "contributions": [
        "code",
        "ideas",
        "question",
        "doc",
        "maintenance",
        "review"
      ]
    }
  ],
  "projectName": "sepal-doc",
  "projectOwner": "openforis",
  "repoType": "github",
  "repoHost": "https://github.com"
}
```

and I created the following AUTHOR.rst file to specify the placement of the fianl table elements : 

```rst 
Thanks goes to these wonderful people (`emoji key <https://allcontributors.org/docs/en/emoji-key>`_):

.. raw:: html
 
    <a href="https://github.com/openforis/sepal-doc/blob/master/AUTHORS.rst">
        <!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
        <img src="https://img.shields.io/badge/all_contributors-1-orange.svg?style=flat-square" alt="All contributors">
        <!-- ALL-CONTRIBUTORS-BADGE:END -->
    </a>

.. raw:: html

    <!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
    <!-- prettier-ignore-start -->
    <!-- markdownlint-disable -->
    <table>
    <tr>
       <td align="center"><a href = "https://12rambau.github.io/web-resume/"><img src="https://avatars.githubusercontent.com/u/12596392?v=4" width="100px;" alt=""/><br /><sub><b>Rambaud Pierrick</b></sub></a></td>
    </tr>
    </table>

    <!-- markdownlint-restore -->
    <!-- prettier-ignore-end -->

    <!-- ALL-CONTRIBUTORS-LIST:END -->


This project follows the `all-contributors <https://allcontributors.org>`_ specification.
Contributions of any kind are welcome!
```

But when I launch the bot, the indentation change and the file is broken.
Do I need to change anything ?

**Comment by Berkmann18** [comment]
That's possibly due to its incompatibility with RST files (cf. #391), I've got no experience with such format so a PR would be welcome for this.

**Comment by 12rambau** [comment]
I' know, that's the issue I first read to understand how I could make it work. 
The bug is just coming from indentation. Ideally it should respect indentation of the `<!-- ALL-CONTRIBUTORS-LIST:START -->`line but that is not the case. I already tried to do a PR on your soft once but that was too far away from what I know, so I'll let this open and we'll see if someone with the appropriate competences is intersted to have a look. 

With this modification you could get the full Python and ReadTheDoc community ;-)

**Comment by Berkmann18** [comment]
What PR was it? I can't seem to find one linked to you.
> With this modification you could get the full Python and ReadTheDoc community ;-)

That would be great 😁, most people in the core team are (I think) mostly focused on JS stuff.

**Comment by 12rambau** [comment]
I tried just there: https://github.com/all-contributors/app/issues/352

I did not manage to understand how all these tests were working.

**Comment by Berkmann18** [comment]
I see, feel free to ask about clarifications of certain parts of the code.

**Comment by 12rambau** [comment]
I'm closing this issue as it is not published in the appropriate repository. I reposted it in the app with a starting point for the solution: https://github.com/all-contributors/app/issues/356
