### ISSUE TITLE
Idea: add projects I contribute to to personal user README

### ISSUE THREAD

**Issue by zepatrik** [all-contributors/all-contributors#521]
**Is your feature request related to a problem? Please describe.**

The current implementation works one-way, where contributors are added to the project.

**Describe the solution you'd like**

It would be nice to add a possibility to reverse that mapping as well and add the projects I contribute to to [my profile's README](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/managing-your-profile-readme).
This could be bound to a config a user first has to apply to avoid unwanted PRs. Once it is set up, every time a user is added/updated in a project's README, the project is also added/updated in the user's README.

**Describe alternatives you've considered**

Don't support that mapping.

**Comment by Berkmann18** [comment]
Sounds like a good idea that would be in a separate tool (be it another CLI or bot or plugin/extension for either).

**Comment by zepatrik** [comment]
Ok right, that makes sense. I will therefore close this issue :wink:
