### ISSUE TITLE
Who can use the all-contributors bot?

### ISSUE THREAD

**Issue by Explosion-Scratch** [all-contributors/all-contributors#529]
It seems that everyone can add anyone for contributions? Or can only people in the organization or with access to the repo use the bot?

**Comment by Explosion-Scratch** [comment]
just testing here

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for bug

**Comment by Explosion-Scratch** [comment]
Ohh, I forgot it makes a PR 🤦🏻

**Comment by Berkmann18** [comment]
Yes, anyone can interact with the bot on repos that are visible to them.
