### ISSUE TITLE
Fonts appear to be natively bold, without possibility to change

### ISSUE THREAD

**Issue by cxaclaudio** [all-contributors/all-contributors#573]
**Is your feature request related to a problem? Please describe.**
I couldn't move to Tabby yet because font characteristics aren't good. If I look over Xshell client, font DejaVu Sans Mono, with size of 9, and font type "normal", it looks ok, not to say perfect. If I try to set DejaVu Sans Mono on Tabby, I need change size to at least 12, and I cannot change font type, from bold to normal. By comparison, tabby appears to have font type set to "Bold" by default. and the characters do not look so clear comparing with Xshell.  

**Describe the solution you'd like**
What I ask is for a clearer font, and ability to set it to normal, bold, italic, whatever.

**Describe alternatives you've considered**
Xshell gives me clear output.

**Additional context**
XShell output:
![xshell7-output](https://user-images.githubusercontent.com/77572140/148990905-3ea75595-a8b5-4791-afa6-f87889ed336d.PNG)

Tabby output:
![tabby-output](https://user-images.githubusercontent.com/77572140/148990908-ae147528-7c07-4ff9-82ae-96be4719af01.PNG)

**Comment by gr2m** [comment]
I don't think this is in any way related to @all-contributors? It seems you wonder who to configure the font for your terminal? I'd search on https://stackoverflow.com/ for questions like this

**Comment by cxaclaudio** [comment]
obviously I don't want anyone to configure my font... for some reason i created this in all-contributors, it was mistake.
