### ISSUE TITLE
Super confused trying to set this up for a GitLab project

### ISSUE THREAD

**Issue by julianstirling** [all-contributors/all-contributors#583]
I am trying to set this up for the OpenFlexure microscope on GitLab.

As a first comment the documentation assumes you have a javascript dev. For those of us who don't have javascript set up it was quite confusing.

After installing I have run init, but check gives me "Project openflexure/openflexure-microscope not found". The GitLab instance is correct, and it is a public repo. I have set a private token for good measure, but this changes nothing.

Is there any way to get a more verbose output for debugging. I have no idea if it is a connection issue, a config issue, a private token issue.

**Comment by tenshiAMD** [comment]
@julianstirling  is this still an issue today? Closing this for now. Feel free to open a new issue if this still occurs.
