### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by Lijiaoa** [all-contributors/all-contributors#590]
I'm a all-contributors cli user. I set 
`"contributorTemplate": "<img src=\"<%= contributor.avatar_url %>\" width=\"<%= options.imageSize %>px;\" alt=\"\"/>",` 
in my `.all-contributorsrc` file.  Contributor will be added when I generate new contributor like this:

![image](https://user-images.githubusercontent.com/61399850/159658291-32062cb2-a6af-4c43-82bc-fdc836f29c60.png)

And I just want this style without the table format. It's impossible? 
`<img src="" width="30px;" alt=""/>`

**Comment by Berkmann18** [comment]
@Lijiaoa So you just want the images and emojis without the table, is that right?

**Comment by tenshiAMD** [comment]
@Lijiaoa Hi. Here's the reference you can read https://allcontributors.org/docs/en/bot/configuration. You can configure the `badgeTemplate ` according to your preference. Let us know if this helps. Closing this for now.
