### ISSUE TITLE
Fix grammar under usage

### ISSUE THREAD

**Issue by willuhm-js** [all-contributors/all-contributors#601]
**Describe the bug**
An Oxford comma and period are required for the grammar to be correct. This comma is the final comma of a list and is missing in the usage section.

For instance,  `@all-contributors please add @jakebolam for infrastructure, tests and code` should be changed to `@all-contributors please add @jakebolam for infrastructure, tests, and code.`

**Screenshots**
![Image](https://i.ibb.co/4KsKG0Q/Screenshot-2022-04-30-7-21-39-PM.png)

**Comment by Berkmann18** [comment]
> @all-contributors please add @jakebolam for infrastructure, tests and code

Seem grammatically correct to me and Grammarly. "@all-contributors please add @jakebolam for infrastructure, tests, and code." seems off to me.

**Comment by willuhm-js** [comment]
The statement is missing a [serial comma](https://en.wikipedia.org/wiki/Serial_comma). Whether or not you plan to include one is up to you, but a list of items should include a comma before the last list item.
