### ISSUE TITLE
@all-contributors Bot 🤖 Installation section incomplete

### ISSUE THREAD

**Issue by BrennerSpear** [all-contributors/all-contributors#613]
**Describe the bug**

When following the @all-contributors Bot 🤖 installation process, there are no instructions of what to add to the readme that will start adding the contributors profiles to the readme

**To Reproduce**
1. follow the [installation](https://allcontributors.org/docs/en/bot/installation) instructions
2. Comment on a PR with a contributor and their contributions

**Expected behavior**
The bot makes a PR to the readme that includes adding the contributor

**Actual behavior**
Bot makes an empty PR to update the readme [example](https://github.com/metagame-xyz/evm-translator/pull/34/commits/8bbce71a370e95dee70f5e5af30fd993d3cb9373)

**Comment by BrennerSpear** [comment]
It's unclear that you ned to use the cli in tandem with the bot to get this into the readme

```

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
```

**Comment by BrennerSpear** [comment]
And now I'm in a spot where it's telling me this. I tried uninstalling and reinstalling the bot and that didn't work :
![Screen Shot 2022-07-22 at 2 23 56 PM](https://user-images.githubusercontent.com/12127609/180500962-3a2f2d89-e42c-4446-b7fb-d20f2d80003c.png)
(

**Comment by MathsionYang** [comment]
@all-contributors please add @<MathsionYang> for <contributions>

**Comment by MathsionYang** [comment]
@all-contributors please add @<MathsionYang> for doc,code

**Comment by MathsionYang** [comment]
@all-contributors please add @MathsionYang  for code

**Comment by tenshiAMD** [comment]
@BrennerSpear hi please check [the update guide](https://allcontributors.org/docs/en/bot/installation#3-create-a-readmemd). I think this solves this kind of confusion.

@Berkmann18 @gr2m I think we can close this issue
