### ISSUE TITLE
[BOT] Multiple commits

### ISSUE THREAD

**Issue by svrooij** [all-contributors/all-contributors#614]
The bot doesn't do a single commit if you have multiple files where the contributors should be present.

**To Reproduce**

1. Configure your repo to show the contributors in multiple files
2. Ask the bot to add someone

**Expected behavior**
I would expect that the created PR would have 1 commit updating all the files, instead it does a commit per changed file

**Screenshots**
![image](https://user-images.githubusercontent.com/1292510/180736970-7587afe9-159e-47f3-844e-6591ee73fe92.png)

**Additional context**
See [this PR](https://github.com/svrooij/node-sonos-ts/pull/167) for instance.

**Comment by gr2m** [comment]
That's is not really a bug, it's just how it's implemented. Updating multiple files in a single commit is much more complicated.

I don't see why this would be a problem? You can squash & merge the changes and get a single commit in your default branch.

Feel free to comment more if you think we are missing something , but I'm going to close the issue as it's not actionable for us

**Comment by svrooij** [comment]
If I'm understanding correctly, it changes the config file and in the config file is a list of files that will be updated.

Apart from that, the repository is "clean" when your bot does a checkout. It can then change all the files and do a `git commit --all` or `git commit files_from_config`.

I was just wondering why it would do four commits (in the case you configured 3 files) instead of just one.

**Comment by gr2m** [comment]
the bot doesn't use `git`, it's using the REST API: https://docs.github.com/en/rest

**Comment by svrooij** [comment]
Then I totally understand the 4 commits. Combining multiple file edits in a single commit, over the rest api is really hard (if even possible).

Just curious, why did you guys choose for using rest instead of git? Any stuff others should consider when creating a bot or similar?

**Comment by gr2m** [comment]
> over the rest api is really hard (if even possible).

It's possible. If you are interested, you can see how in this code:
https://github.com/gr2m/octokit-plugin-create-pull-request/blob/main/src/compose-create-pull-request.ts

I plan on creating a "create-or-update-multiple-files" Octokit plugin out of that code for a while, just didn't get around to it yet :) 

> Just curious, why did you guys choose for using rest instead of git? Any stuff others should consider when creating a bot or similar?

The app runs on a serverless environment with very restricted system access. Even if we had `git`, the operations would be much slower than directly changing files on GitHub using their APIs
