### ISSUE TITLE
Bot defaults to a broken contributors link

### ISSUE THREAD

**Issue by PickleNik** [all-contributors/all-contributors#615]
**Describe the bug**
Bot's badgeTemplate defaults to a link with a dash(-) for emoji, like in your README.md.
<img width="508" alt="Screen Shot 2022-08-20 at 4 46 11 PM" src="https://user-images.githubusercontent.com/31113245/185765438-3ec84c20-b44a-4124-ac68-f1f779698d7f.png">

**To Reproduce**
Regular bot usage with default rc.

**Expected behavior**
Most repos won't have the emoji next to #contributors section title, so the link would be broken by default.
<img width="1012" alt="Screen Shot 2022-08-20 at 4 47 58 PM" src="https://user-images.githubusercontent.com/31113245/185765492-e698433d-43d3-4915-bbbb-50bb1af64bf3.png">

**Screenshots**
<img width="966" alt="Screen Shot 2022-08-20 at 4 48 17 PM" src="https://user-images.githubusercontent.com/31113245/185765504-816937fb-1964-437b-b2d7-8c07051606d8.png">

**Additional context**
I propose to change bot's default badgeTemplate to not have the dash(-)

**Comment by tenshiAMD** [comment]
@PickleNik Issue has been resolved. I think you can close this anytime soon.

**Comment by PickleNik** [comment]
> @PickleNik Issue has been resolved. I think you can close this anytime soon.

No but the bot still defaults to it without changing the template, this issue was meant to change the bot's defaults at first installation for future projects.

**Comment by tenshiAMD** [comment]
@PickleNik I think the configuration is wrong. I tested mine [here](https://github.com/ruby-gh-actions/sandbox-mergeable/edit/main/README.md) and the bot did not change the URL at all.

**Comment by tenshiAMD** [comment]
@PickleNik Also, I think you should file this issue in [bot repo](https://github.com/all-contributors/app) instead.

**Comment by PickleNik** [comment]
> [here](https://github.com/ruby-gh-actions/sandbox/blob/main/README.md) 

links to 404 for me

**Comment by PickleNik** [comment]
> @PickleNik Also, I think you should file this issue in [bot repo](https://github.com/all-contributors/app) instead.

oh ight, I didn't find it the first time

**Comment by tenshiAMD** [comment]
> links to 404 for me

 @PickleNik I updated it, check the link again.

**Comment by PickleNik** [comment]
> @PickleNik I updated it, check the link again.

Still 404s, I don't think I have access to it.

**Comment by PickleNik** [comment]
> [bot repo](https://github.com/all-contributors/app) instead.

Re-opened this issue [there](https://github.com/all-contributors/app/issues/400)

**Comment by tenshiAMD** [comment]
@PickleNik my bad, I forgot the repo is private, try now.

**Comment by PickleNik** [comment]
> @PickleNik my bad, I forgot the repo is private, try now.
So this is with the default config and you added yourself via the bot?

**Comment by tenshiAMD** [comment]
> So this is with the default config and you added yourself via the bot?

@PickleNik yes

**Comment by PickleNik** [comment]
> @PickleNik yes

Interesting, thanks, I'll try it on my own repo later and close [the issue](https://github.com/all-contributors/app/issues/400) if it works correctly.
