### ISSUE TITLE
New emoji for "data" or "content"?

### ISSUE THREAD

**Issue by patcon** [all-contributors/all-contributors#63]
For many projects that also involve a live website, part of the project that may be within scope of the developer community is "data" or more generally "content". Yes, on some types of website, the "content" category could be so large and organic that it's not useful to have it in README, but for others, it might be a group small enough that they deserve special recognition among other contributors.

For example, the [`edgi-govdata-archiving/web-monitoring`](http://github.com/edgi-govdata-archiving/web-monitoring) project is building out a pipeline for monitoring government webpage changes, and funneling the important changes past domain experts and to media partners. We have whole classes of contributors who aggregate and manage the list of webpages to monitor, and also the non-technical analysts who help us sort through the noise.

I would be nice to use `all-contributors` to recognize how these folks contribute to the project, but the current categories don't seem to fit.

Potential emoji: :1234:

**Comment by kentcdodds** [comment]
I love it. Yes, feel free to [open a PR](http://makeapullrequest.com/) to add this to the spec, then you can make another on [the CLI repo](https://github.com/jfmengels/all-contributors-cli) :+1:

Thanks!

**Comment by Berkmann18** [comment]
@patcon Mind opening a PR for this?

**Comment by Berkmann18** [comment]
As the `content` category is available, I'll close this issue.
