### ISSUE TITLE
Typo: Login block > property acessCodePlaceholder

### ISSUE THREAD

**Issue by ocBruno** [all-contributors/all-contributors#630]
There is a typo in the acessCodePlaceholder prop 
https://prnt.sc/ZMeOWFyHdE9i

**Comment by tenshiAMD** [comment]
@ocBruno looks like you have mistake. That's for a different repo.

**Comment by ocBruno** [comment]
@tenshiAMD Ahh pardon tenshi and thanks for the heads up
