### ISSUE TITLE
Enforce markdownlint

### ISSUE THREAD

**Issue by tenshiAMD** [all-contributors/all-contributors#632]
I suggest enforcing [markdownlint](https://github.com/DavidAnson/markdownlint).

**Comment by Berkmann18** [comment]
That's a good idea.

**Comment by Roshanjossey** [comment]
markdownlint can be run as a pre-commit hook [example from eslint](https://github.com/eslint/eslint/blob/d75d3c68ad8c98828aaa522b87ec267ab2dcb002/package.json#L38)

I think it also makes sense to add it as a GitHub action to have a check on PRs for additional safety.
