### ISSUE TITLE
Missing different languages documentation URLs

### ISSUE THREAD

**Issue by theranjitraut** [all-contributors/all-contributors#651]
Missing different languages documentation URLs

**To Reproduce**
1. Go to https://github.com/all-contributors/all-contributors
2. Scroll down to '**Read this documentation in the following languages**'
3. Click on URLs of different documentation
4. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/67329253/194765822-53e13d46-b25e-4a4a-b150-83da41e0b531.png)

**Missing URLs**
![image](https://user-images.githubusercontent.com/67329253/194766092-4d9c51fb-d824-4409-be92-61d01c353b2b.png)

**Comment by Berkmann18** [comment]
That's a good point, although the languages listed there are those manually translated and maintained via the repo whereas we use Crowdin which has a much wider set of languages with mostly up-to-date translations.
