### ISSUE TITLE
Add an "open science contributor" to the Emoji Key

### ISSUE THREAD

**Issue by bello-mart-isabella** [all-contributors/all-contributors#659]
**Is your feature request related to a problem? Please describe.**
We'd like to honor everyone who uses our resources at NASA Transform to Open Science (TOPS) for utilizing our materials for open science! They aren't exactly a contributor to our code, but users, so the existing emoji's don't quite have the description we're looking for.

**Describe the solution you'd like**
We'd love an "open science" emoji option, maybe using a telescope or test tube as the icon?

**Comment by Berkmann18** [comment]
That seems to be way too generic, especially given most projects using AC will be Open Source (at least to an extent) and users that go on the AC table for a project will do for more specific contributions like gathering data, answering questions, raising/fixing bugs, improving the documentation, helping in the research etc.

**Comment by bello-mart-isabella** [comment]
Understood - thank you!
