### ISSUE TITLE
This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token ] in JSON at position 1255

### ISSUE THREAD

**Issue by msmygit** [all-contributors/all-contributors#690]
**Describe the bug**
This doesn't work as expected.

**To Reproduce**
1. Installed and configured per instructions
2. Made a minor change and submitted a PR.
3. Note that I want the contributors to go into both readme as well as contributing files and hence `files` array has both
4. Updated the `.all-contributorsrc` JSON file with instructions from https://allcontributors.org/docs/en/bot/configuration . Of course, updated both projectOwner and projectName fields to match my repo as below:
```
{ 
  "projectName": "projectOwner",
  "projectOwner": "projectName",
  "repoType": "github",
  "repoHost": "https://github.com",
  "files": ["README.md","CONTRIBUTING.md"],
  "imageSize": 50,
  "commit": false,
  "contributorsPerLine": 7,
  "contributorsSortAlphabetically": false,
  "badgeTemplate": "[![All Contributors](https://img.shields.io/github/all-contributors/<%= projectOwner %>/<%= projectName %>?color=ee8449&style=flat-square)](#contributors)",
  "contributorTemplate": "<a href=\"<%= contributor.profile %>\"><img src=\"<%= contributor.avatar_url %>\" width=\"<%= options.imageSize %>px;\" alt=\"\"/><br /><sub><b><%= contributor.name %></b></sub></a>",
  "types": {
    "custom": {
      "symbol": "🔭",
      "description": "A custom contribution type.",
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
  "linkToUsage": true,
  "skipCi": true,
  "contributors": []
}
```
FWIW, I did not update the `badgeTemplate` line as it appears to correctly use substitutions for the project owner and name fields from above.

5. When commented `@all-contributors please add @githubhandle for ideas` all I see in the PR is below error:
```
This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token ] in JSON at position 1255
```

**Expected behavior**
It should seamlessly add the contributor for the given type (`ideas` here in my case)

**Screenshots**
n/a

**Additional context**

**Comment by msmygit** [comment]
FWIW, even if I remove the `types` section, it errors with the same message

**Comment by msmygit** [comment]
@all-contributors-release-bot please add @msmygit for ideas

**Comment by msmygit** [comment]
@all-contributors please add @msmygit for bug

**Comment by msmygit** [comment]
Even the same error when I remove `badgeTemplate` as well as `contributorTemplate` lines too.

**Comment by msmygit** [comment]
> @msmygit
> 
> I've put up [a pull request](https://github.com/all-contributors/all-contributors/pull/691) to add @msmygit! 🎉

not sure how this works!! `¯\_(ツ)_/¯`

**Comment by msmygit** [comment]
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/19366623/217272764-271ac1be-05c1-4c28-9ae4-06fbc64d1003.png">
Even I validated the JSON at jsonformatter.org and it has no issues.

**Comment by msmygit** [comment]
It was an user error. closing this issue.

**Comment by danieltott** [comment]
@msmygit what was the error?!?
