### ISSUE TITLE
react and react-dom dependencies on angular app

### ISSUE THREAD

**Issue by nicoesiea** [all-contributors/all-contributors#701]
**Is your feature request related to a problem? Please describe.**
When I try to install npm dependencies for "@ohif/viewer": "^4.12.51", on an angular project, using:     "react": "^18.0.2" and "react-dom": "^18.2.0", I always got this error:
npm ERR! While resolving: tm-microscopy-ui@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.2" from the root project        
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @ohif/viewer@4.12.51 
npm ERR! node_modules/@ohif/viewer
npm ERR!   @ohif/viewer@"^4.12.51" from the root project

**Describe the solution you'd like**
Update the npm version with a new version working with react 18

**Describe alternatives you've considered**
For now, a solution I found could be to downgrade my react lib, but I have others plugins which need it too

**Additional context**
node v16.18.1
angular 13
typescript ~4.6.4

**Comment by Berkmann18** [comment]
It seems like you posted that in the wrong repo.
