### ISSUE TITLE
all-contributors bot available in private repos ?

### ISSUE THREAD

**Issue by LBF38** [all-contributors/all-contributors#713]
Hi there ! Love the project and open source community.
Just a quick question to know if the all-contributors bot (GH App) can work on private repos / private orgs to manage contributors, even though it is meant for open source projects.
Thx for your answer !

**Comment by AoifeHughes** [comment]
Yes, it does, follow the install instructions and you can add private repos no problem.

**Comment by LBF38** [comment]
Thank you for your answer

That's what I have done with my repo [Syncthing integration for Obsidian](https://github.com/LBF38/obsidian-syncthing-integration) before making it public. But it didn't work until I make it public, that's why I asked for. 

Is there any particular setup to give to the bot ?

**Comment by AoifeHughes** [comment]
https://allcontributors.org/docs/en/bot/installation

**Comment by LBF38** [comment]
That's what I've followed, might have missed something. 
Thanks
