### ISSUE TITLE
How to change the mark icon in map

### ISSUE THREAD

**Issue by sudheer160540** [all-contributors/all-contributors#75]
How to change the mark icon in map

**Comment by kentcdodds** [comment]
Could you clarify? What mark icon? Do you mean how do you customize the emoji? This is not currently possible. I'm not opposed to making it configurable though if you'd like to [make a pull request](http://makeapullrequest.com) :)

**Comment by Berkmann18** [comment]
@sudheer160540 Please expand on that.

**Comment by MatheusRV** [comment]
@Berkmann18 remove help-wanted and add wating for feedback

**Comment by Berkmann18** [comment]
@MatheusRV Good point.

**Comment by Berkmann18** [comment]
@sudheer160540 Friendly ping.
