### ISSUE TITLE
G

### ISSUE THREAD

**Issue by asanpardazzagrosheyrani** [all-contributors/all-contributors#798]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example, "I'm always frustrated when [...]"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asanpardazzagrosheyrani** [comment]
سلام عرض ادب خسته نباشید ❤️ متامسک کی میشه ازش استفاده کنم خیلی گیرم 🌹🙏
heyrani

در تاریخ پنجشنبه ۵ سپتامبر ۲۰۲۴،‏ ۱۲:۰۶ a.p.z. eth ***@***.***>
نوشت:

**Comment by asanpardazzagrosheyrani** [comment]
heyrani

در تاریخ پنجشنبه ۵ سپتامبر ۲۰۲۴،‏ ۱۲:۳۲ a.p.z. eth ***@***.***>
نوشت:

**Comment by Ans075** [comment]
Translate

**Comment by Ans075** [comment]
I don't know language
