### ISSUE TITLE
Add Category for committer

### ISSUE THREAD

**Issue by jayvdb** [all-contributors/all-contributors#81]
Being a committer is more than just code.

This becomes especially important for repos which do fast-forward commits, as their effort does not appear in the repository, and so repository based analysis tools omit this.

e.g. https://github.com/PyCQA/pyflakes/commit/9dd73ec544 is a fast-forward commit by a non-committer, merged manually by a committer.  i.e. me.

Also GitHub does not provide any public way to determine who are the committers.  It only shows "Contributor" / "Org member", which doesnt indicate whether someone has "Push" rights or not.

Exposing this role in the contributor registry as a separate category seems like a logical choice.

**Comment by kentcdodds** [comment]
That sounds fine to me. What emoji do you propose?

**Comment by RandomGuyDTB** [comment]
In my opinion a chain would be an okay idea for the emoji because next to the commit button when editing a file on the website there's a picture that looks like a chain, it's just that the original use for that was to symbolize committing to the master branch so it'd be kind of weird to transplant the icon with a different purpose. I second this, a committer icon would be great. Thinking of one is pretty difficult though.

**Comment by kentcdodds** [comment]
I'm good with 🔗

**Comment by Berkmann18** [comment]
@jakebolam @sinchang

**Comment by Berkmann18** [comment]
@jayvdb [I added a maintainer category](https://github.com/all-contributors/all-contributors/commit/d4e90815e777664f7a6d4e79edb6eb8e465e729a) and I was wondering if that was covering the committer category or not?

**Comment by MatheusRV** [comment]
> @jayvdb [I added a maintainer category](https://github.com/all-contributors/all-contributors/commit/d4e90815e777664f7a6d4e79edb6eb8e465e729a) and I was wondering if that was covering the committer category or not?

Vote to close this in favor of maintainer.

**Comment by MatheusRV** [comment]
> I'm good with 🔗

Ugly emoji for this, Maintainer is beatiful 🚧. More intuitive.

**Comment by kentcdodds** [comment]
I'm ambivalent.

**Comment by sinchang** [comment]
> @jayvdb [I added a maintainer category](https://github.com/all-contributors/all-contributors/commit/d4e90815e777664f7a6d4e79edb6eb8e465e729a) and I was wondering if that was covering the committer category or not?

I think it's enough we already have maintainer category
