### ISSUE TITLE
Minimal Version

### ISSUE THREAD

**Issue by matbrgz** [all-contributors/all-contributors#85]
Suggesting this repository for another project that I find interesting I came across a rather interesting idea:

"
I would actually like to see the minimal version of that list, one with only the Avatar + GitHub profile (or website) link. From my perspective, if it does not really matter if it was a bug, a PR code, a translation or some documentation, in the end it's a contribution and it should be recognized as a contributor, without all those emoji and huge avatar
"
@goenning in https://github.com/getfider/fider/issues/612

What do you think? Very cool in my opinion.

**Comment by kentcdodds** [comment]
I'd be fine with that. Feel free to PR to the spec to add a note about a minimal version being acceptable.

**Comment by Berkmann18** [comment]
@MatheusRV Have you started working on that?

**Comment by MatheusRV** [comment]
> @MatheusRV Have you started working on that?

Not yet.

**Comment by MatheusRV** [comment]
https://github.com/twbs/bootstrap/issues/27567#issuecomment-434578164

**Comment by MatheusRV** [comment]
Just a ideia

![chrome_31dhmtxpt3](https://user-images.githubusercontent.com/23284276/52488413-e949bc80-2ba6-11e9-8390-1c950ea3447e.png)

https://getbootstrap.com/docs/4.2/about/team/

**Comment by Berkmann18** [comment]
That looks good to although I believe it wouldn't be similar enough to the current AC table style/format with less info (e.g. no contribution emojis).

**Comment by MatheusRV** [comment]
> That looks good to although I believe it wouldn't be similar enough to the current AC table style/format with less info (e.g. no contribution emojis).

I think where is follow the emoji, we could improve this.

**Comment by Berkmann18** [comment]
@MatheusRV The column view, that's already configurable; where the `"contributorsPerLine"` property in `.all-contributorsrc` could be set to `2`.

I think it's definitely a good idea to have a place where visitors can 1-click to follow someone (which could be placed where contribution emojis are?)

**Comment by MatheusRV** [comment]
Awesome reference https://github.com/ipfs/contributors-hex-grid#interplanetary-contributors-webpage

**Comment by jvican** [comment]
I'd prefer a version that follows up on the minimal idea suggestion in the first comment, where the table only contains images and names. I currently do this manually in my project https://github.com/scalacenter/bloop but it's a little bit frustrating that the bot doesn't work if it doesn't recognise any contribution. I'd love if the bot could just append a contributor with no specific icon.

**Comment by mrchief** [comment]
A minimal version would be wonderful! 

In the meantime, switching to a markdown table would be helpful in reducing the readme size.

**Comment by Berkmann18** [comment]
@jvican 
> the bot doesn't work if it doesn't recognise any contribution. I'd love if the bot could just append a contributor with no specific icon

You can use the `maintenance` category (i.e. `@all-... please add x for maintenance`) and that should work fine, then you'll just need to remove the icons.

**Comment by jvican** [comment]
>  then you'll just need to remove the icons.
  
Do you mean I'll need to remove the icons manually from the PR created by the bot?

**Comment by Berkmann18** [comment]
@mrchief 
> In the meantime, switching to a markdown table would be helpful in reducing the readme size.

True, and we may re-introduce it alongside the HTML option (cf. https://github.com/all-contributors/all-contributors-cli/issues/173).

@jvican 
> Do you mean I'll need to remove the icons manually from the PR created by the bot? What I want is the bot to add someone in the contributor list while not adding any icon at all. Otherwise, it defeats the purpose and it's just better to add that person manually.

At the moment, yes as both the CLI and the bot requires at least one contribution type to be specified (at least until there's a minimal version implemented).

I see what you're trying to do and I'm wondering why you want to omit the contribution icons.

**Comment by jvican** [comment]
> I see what you're trying to do and I'm wondering why you want to omit the contribution icons.
  
I want something that automates the addition of new people to the contributor list but I don't want to acknowledge (or think about) what kind of contributions they do. The contributors in my projects work on too many different things and the table goes rapidly out-of-date, so I just want their nice avatar in my README to credit them for *any* work instead of some *specific* domain work.
  
If someone is interested in who has which rights, they usually ask in Gitter (though it's uncommon, people just ask for reviews, they don't ask who's in charge of what).

**Comment by Berkmann18** [comment]
> I want something that automates the addition of new people to the contributor list but I don't want to acknowledge (or think about) what kind of contributions they do. The contributors in my projects work on too many different things and the table goes rapidly out-of-date, so I just want their nice avatar in my README to credit them for any work instead of some specific domain work.

That makes sense, in that case (for now) using the `maintenance` category would be the way to go (at least until someone gets a minimal version working and released).

**Comment by maphew** [comment]
I like the look of the above [bootstrap example](https://github.com/all-contributors/all-contributors/issues/85#issuecomment-461843599) best. It has room for contribution type emojis for those who track that. Also +1 for markdown table as option instead of html.

**Comment by kytwb** [comment]
We wanted to do something like (this is from Open Collective, based on the GitHub contributions graph only):

![All Contributors](https://opencollective.com/getferdi/contributors.svg?width=890&button=false)

> Unfortunately, this is not what we want as we also want to list contributors who spend time to help investigating issues, give feedback and such (which GitHub doesn't account for).

What we managed to do for now:

<img width="929" alt="Screen Shot 2019-12-19 at 4 32 31 PM" src="https://user-images.githubusercontent.com/412895/71186290-427d8480-227d-11ea-95f1-31e453b235f5.png">

I guess we would need to be able to get rid of the table (or at least style it to remove the borders) and maybe use a microservice to return circular avatars (as we can't use `border-radius`).

Via https://github.com/getferdi/ferdi/issues/236

**Comment by kytwb** [comment]
Quick update on the latest attempt here.
I edited all-contributors-cli locally to change [generateContributorsList](https://github.com/all-contributors/all-contributors-cli/blob/db5d731d964102aa7bd88ae280dd93160b2e31c9/src/generate/index.js#L46).

<img width="524" alt="Screen Shot 2020-04-21 at 11 55 28 PM" src="https://user-images.githubusercontent.com/412895/79926253-f2315180-842b-11ea-86ef-9a713c27f68a.png">

Via https://github.com/getferdi/ferdi/pull/266#issuecomment-617470631.

**Comment by kytwb** [comment]
I was thinking of using a fork with the local hack as dependency for all-contributors-cli, but that wouldn't work as we most often use the GitHub bot, which would generate the contributors list using the official version. We will have to contribute to all-contributors-cli if we want the minimal version 😛

**Comment by jdalrymple** [comment]
To get the circuluar icons, one could use this template:

```json
"contributorTemplate": "<a href=\"<%= contributor.profile %>\"><img src=\"https://images.weserv.nl/?url=<%= contributor.avatar_url %>&h=<%= options.imageSize %>&w=<%= options.imageSize %>&fit=cover&mask=circle&maxage=7d\" alt=\"<%= contributor.name %>\"/>",
```

All we need now is a configurable way to specify the wrapper element (basically to change from 'table' to 'p')

This results in this output:

![image](https://user-images.githubusercontent.com/3743662/209407742-05d73099-9567-4e66-8e06-51314ca3c38d.png)

**Comment by jdalrymple** [comment]
Just waiting for the merge :raised_hands:
